---
# SSH hardening

- name: Deploy hardened sshd_config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: "{{ system_base_sshd_config_path | default('/etc/ssh/sshd_config') }}"
    owner: root
    group: root
    mode: '0600'
  notify: Restart sshd

- name: Ensure sshd service is enabled and started
  ansible.builtin.service:
    name: "{{ system_base_sshd_service | default('sshd') }}"
    enabled: true
    state: started
