---
- name: Validate node type
  ansible.builtin.assert:
    that:
      - netdata_node_type in ['standalone', 'child', 'parent', 'proxy']
    fail_msg: 'Invalid netdata_node_type: {{ netdata_node_type }}. Must be one of: standalone, child, parent, proxy'
  tags:
    - netdata
    - netdata-streaming

- name: Retrieve streaming API keys from Infisical
  when: netdata_use_infisical and (netdata_node_type in ['child', 'parent'])
  block:
    - name: Get Infisical secrets
      infisical.vault.read_secrets:
        path: '{{ netdata_infisical_path }}'
        env_slug: "{{ infisical_environment | default('prod') }}"
      register: netdata_secrets
      no_log: true

    - name: Set API key from Infisical for child node
      ansible.builtin.set_fact:
        netdata_streaming_api_key: '{{ netdata_secrets.secrets.NETDATA_STREAMING_API_KEY }}'
      when:
        - netdata_node_type == 'child'
        - netdata_secrets.secrets.NETDATA_STREAMING_API_KEY is defined
      no_log: true

    - name: Set API key from Infisical for parent node
      ansible.builtin.set_fact:
        netdata_parent_api_key: '{{ netdata_secrets.secrets.NETDATA_PARENT_API_KEY }}'
      when:
        - netdata_node_type == 'parent'
        - netdata_secrets.secrets.NETDATA_PARENT_API_KEY is defined
      no_log: true
  tags:
    - netdata
    - netdata-streaming
    - netdata-secrets

- name: Configure child node streaming
  ansible.builtin.include_tasks: configure-child.yml
  when: netdata_node_type == 'child'
  tags:
    - netdata
    - netdata-streaming
    - netdata-child

- name: Configure parent node streaming
  ansible.builtin.include_tasks: configure-parent.yml
  when: netdata_node_type == 'parent'
  tags:
    - netdata
    - netdata-streaming
    - netdata-parent

- name: Configure proxy node
  ansible.builtin.include_tasks: configure-proxy.yml
  when: netdata_node_type == 'proxy'
  tags:
    - netdata
    - netdata-streaming
    - netdata-proxy

- name: Deploy streaming configuration
  ansible.builtin.template:
    src: stream.conf.j2
    dest: '{{ netdata_config_dir }}/stream.conf'
    owner: '{{ netdata_user }}'
    group: '{{ netdata_group }}'
    mode: '0640'
    backup: true
  when: netdata_node_type != 'standalone'
  notify: restart netdata
  tags:
    - netdata
    - netdata-streaming

- name: Configure SSL/TLS for streaming
  ansible.builtin.include_tasks: configure-ssl.yml
  when:
    - netdata_streaming_ssl_enabled
    - netdata_node_type != 'standalone'
  tags:
    - netdata
    - netdata-streaming
    - netdata-ssl
