---
# Disable Statsd in Netdata configuration on all nodes
- name: Disable Statsd plugin in Netdata
  hosts: all:!localhost
  become: true
  gather_facts: false
  
  tasks:
    - name: Check if netdata.conf exists
      stat:
        path: /etc/netdata/netdata.conf
      register: netdata_conf_file
    
    - name: Check current Statsd configuration
      shell: |
        grep -A2 '^\[statsd\]' /etc/netdata/netdata.conf || echo "No statsd section found"
      register: current_statsd_config
      changed_when: false
      when: netdata_conf_file.stat.exists
    
    - name: Display current Statsd configuration
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          Current config:
          {{ current_statsd_config.stdout }}
      when: 
        - netdata_conf_file.stat.exists
        - "'statsd' in current_statsd_config.stdout"
    
    - name: Disable Statsd plugin
      shell: |
        sed -i '/^\[statsd\]/,/^\[/{s/enabled = yes/enabled = no/}' /etc/netdata/netdata.conf
      when: 
        - netdata_conf_file.stat.exists
        - "'[statsd]' in current_statsd_config.stdout"
        - "'enabled = yes' in current_statsd_config.stdout"
      register: statsd_disabled
      changed_when: true
    
    - name: Comment out Statsd bind configuration
      replace:
        path: /etc/netdata/netdata.conf
        regexp: '^(\s*bind to\s*=.*statsd.*)'
        replace: '# \1  # Disabled - Statsd not in use'
      when: 
        - netdata_conf_file.stat.exists
        - "'[statsd]' in current_statsd_config.stdout"
      register: statsd_bind_commented
    
    - name: Restart Netdata if configuration changed
      systemd:
        name: netdata
        state: restarted
      when: statsd_disabled.changed or statsd_bind_commented.changed
      register: netdata_restarted
    
    - name: Wait for Netdata to be ready
      wait_for:
        port: 19999
        host: "{{ ansible_host | default(inventory_hostname) }}"
        delay: 3
        timeout: 30
      when: netdata_restarted.changed
    
    - name: Report changes
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          Statsd disabled: {{ statsd_disabled.changed | default(false) }}
          Bind commented: {{ statsd_bind_commented.changed | default(false) }}
          Netdata restarted: {{ netdata_restarted.changed | default(false) }}
      when: statsd_disabled.changed or statsd_bind_commented.changed