---
# Fix Netdata web server and IP address issues
# - Enables web server on all nodes
# - Fixes IP address in Consul registration (10.xx → 11.xx)
# Usage: uv run ansible-playbook playbooks/infrastructure/monitoring/fix-netdata-web-and-ip.yml -i inventory/doggos-homelab/infisical.proxmox.yml

- name: Fix Netdata web server and IP configuration
  hosts: ~nomad.*
  become: true
  vars:
    # Override to ensure web server is enabled
    netdata_web_enabled: true
    netdata_bind_to: "*"
    netdata_port: 19999
    
  tasks:
    - name: Get correct 192.168.11.x IP address
      ansible.builtin.set_fact:
        ansible_default_ipv4: 
          address: "{{ ansible_all_ipv4_addresses | select('match', '^192\\.168\\.11\\.') | first | default(ansible_default_ipv4.address) }}"
          interface: "{{ ansible_default_ipv4.interface }}"
          netmask: "{{ ansible_default_ipv4.netmask }}"
          network: "{{ ansible_default_ipv4.network }}"
          
    - name: Display corrected IP
      ansible.builtin.debug:
        msg: "Using IP {{ ansible_default_ipv4.address }} for {{ inventory_hostname }}"

    - name: Apply Netdata role with corrected settings
      ansible.builtin.include_role:
        name: netdata
        tasks_from: configure
        
    - name: Ensure web server mode is set in [web] section
      ansible.builtin.lineinfile:
        path: /etc/netdata/netdata.conf
        regexp: '^\s*mode\s*='
        line: '    mode = static-threaded'
        insertafter: '^\[web\]'
        state: present
        backup: true
      register: web_config_fixed

    - name: Fix IP address in Consul service registration
      ansible.builtin.replace:
        path: /etc/consul.d/netdata.json
        regexp: '192\.168\.10\.\d+'
        replace: "{{ ansible_all_ipv4_addresses | select('match', '^192\\.168\\.11\\.') | first }}"
        backup: true
      register: consul_service_fixed
      when: ansible_all_ipv4_addresses | select('match', '^192\\.168\\.11\\.') | list | length > 0

    - name: Restart Netdata if config changed
      ansible.builtin.systemd:
        name: netdata
        state: restarted
      when: web_config_fixed.changed

    - name: Reload Consul to pick up service changes
      ansible.builtin.systemd:
        name: consul
        state: reloaded
      when: consul_service_fixed.changed | default(false)
      failed_when: false

    - name: Verify Netdata web interface
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}:19999/api/v1/info"
        method: GET
        status_code: 200
      register: web_check
      failed_when: false

    - name: Report status
      ansible.builtin.debug:
        msg:
          - "{{ inventory_hostname }}: {{ 'SUCCESS' if web_check.status == 200 else 'FAILED' }}"
          - "IP: {{ ansible_default_ipv4.address }}"
          - "Web interface: {{ 'ONLINE' if web_check.status == 200 else 'OFFLINE' }}"