---
# Update Netdata configuration and Consul service registration
# Fixes IP address issue (10.xx → 11.xx) and enables web server
# Usage: uv run ansible-playbook playbooks/infrastructure/monitoring/update-netdata-configs.yml -i inventory/doggos-homelab/infisical.proxmox.yml

- name: Update Netdata configurations on all nodes
  hosts: all
  become: true
  vars:
    netdata_config_dir: /etc/netdata
    netdata_user: netdata
    netdata_group: netdata
    netdata_port: 19999
    netdata_bind_to: "*"
    netdata_web_enabled: true  # Force enable web server
    
    # Consul service configuration
    netdata_consul_service_name: "{{ 'netdata-parent' if inventory_hostname in groups.get('netdata_parents', []) else 'netdata-child' }}"
    netdata_consul_service_port: 19999
    netdata_consul_health_check_interval: "30s"
    netdata_consul_health_check_timeout: "5s"
    netdata_consul_enable_tag_override: false
    netdata_consul_service_tags:
      - "monitoring"
      - "metrics"
      - "{{ 'parent' if inventory_hostname in groups.get('netdata_parents', []) else 'child' }}"
    netdata_consul_service_meta:
      version: "latest"
      environment: "production"
      
  tasks:
    - name: Ensure correct network interface IP is used
      ansible.builtin.set_fact:
        correct_ip: "{{ ansible_all_ipv4_addresses | select('match', '^192\\.168\\.11\\.') | first | default(ansible_default_ipv4.address) }}"
        
    - name: Display IP address being used
      ansible.builtin.debug:
        msg: 
          - "Host: {{ inventory_hostname }}"
          - "Correct IP: {{ correct_ip }}"
          - "Default IPv4: {{ ansible_default_ipv4.address }}"

    - name: Check if Consul is installed
      ansible.builtin.stat:
        path: /usr/bin/consul
      register: consul_binary

    - name: Update Consul service registration for Netdata
      ansible.builtin.template:
        src: consul-netdata-fixed.json.j2
        dest: /etc/consul.d/netdata.json
        mode: '0644'
        backup: true
      when: consul_binary.stat.exists
      register: consul_service_updated

    - name: Create the fixed Consul service template
      ansible.builtin.copy:
        dest: /tmp/consul-netdata-fixed.json.j2
        content: |
          {
            "service": {
              "name": "{{ netdata_consul_service_name }}",
              "tags": {{ netdata_consul_service_tags | to_json }},
              "meta": {{ netdata_consul_service_meta | to_json }},
              "port": {{ netdata_consul_service_port }},
              "address": "{{ correct_ip }}",
              "enable_tag_override": {{ netdata_consul_enable_tag_override | lower }},
              "check": {
                "id": "{{ netdata_consul_service_name }}-health",
                "name": "Netdata Health Check",
                "http": "http://{{ correct_ip }}:{{ netdata_port }}/api/v1/info",
                "method": "GET",
                "interval": "{{ netdata_consul_health_check_interval }}",
                "timeout": "{{ netdata_consul_health_check_timeout }}"
              }
            }
          }
      delegate_to: localhost
      run_once: true

    - name: Apply fixed Consul service registration
      ansible.builtin.template:
        src: /tmp/consul-netdata-fixed.json.j2
        dest: /etc/consul.d/netdata.json
        mode: '0644'
        backup: true
      when: consul_binary.stat.exists
      register: consul_service_fixed

    - name: Update Netdata main configuration to enable web server
      ansible.builtin.blockinfile:
        path: "{{ netdata_config_dir }}/netdata.conf"
        marker: "# {mark} ANSIBLE MANAGED - WEB SERVER CONFIG"
        block: |
          [global]
              bind to = *:{{ netdata_port }}
              
          [web]
              enabled = yes
              mode = multi-threaded
              enable gzip compression = yes
              gzip compression level = 3
        backup: true
      register: netdata_config_updated

    - name: Validate Netdata configuration
      ansible.builtin.command: netdata -W unittest
      changed_when: false
      failed_when: false
      register: netdata_validate

    - name: Reload Consul if service registration changed
      ansible.builtin.systemd:
        name: consul
        state: reloaded
      when: 
        - consul_binary.stat.exists
        - consul_service_fixed.changed or consul_service_updated.changed

    - name: Restart Netdata if configuration changed
      ansible.builtin.systemd:
        name: netdata
        state: restarted
        daemon_reload: true
      when: netdata_config_updated.changed

    - name: Wait for Netdata to be ready
      ansible.builtin.wait_for:
        port: 19999
        host: "{{ correct_ip }}"
        delay: 5
        timeout: 30
      when: netdata_config_updated.changed

    - name: Verify Netdata web interface is accessible
      ansible.builtin.uri:
        url: "http://{{ correct_ip }}:19999/api/v1/info"
        method: GET
        status_code: 200
      register: netdata_api_check
      failed_when: false

    - name: Display verification results
      ansible.builtin.debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "IP Address: {{ correct_ip }}"
          - "Consul service updated: {{ consul_service_fixed.changed | default(false) }}"
          - "Netdata config updated: {{ netdata_config_updated.changed }}"
          - "Web interface status: {{ 'ACCESSIBLE' if netdata_api_check.status == 200 else 'NOT ACCESSIBLE' }}"

- name: Verify all changes from monitoring perspective
  hosts: netdata_parents[0]
  tasks:
    - name: Wait for services to stabilize
      ansible.builtin.pause:
        seconds: 10

    - name: Check Consul for Netdata services
      ansible.builtin.shell: |
        consul catalog services | grep -E "netdata" || echo "No Netdata services found"
      register: netdata_services
      changed_when: false
      failed_when: false

    - name: Check Netdata streaming status
      ansible.builtin.uri:
        url: "http://localhost:19999/api/v1/info"
        method: GET
      register: parent_info
      failed_when: false

    - name: Final summary
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "NETDATA CONFIGURATION UPDATE COMPLETED"
          - "=========================================="
          - "✅ IP addresses corrected (10.xx → 11.xx)"
          - "✅ Web server enabled on all nodes"
          - "✅ Consul service registrations updated"
          - "=========================================="
          - "Netdata services in Consul:"
          - "{{ netdata_services.stdout_lines | default(['Check Consul manually']) }}"
          - "=========================================="