# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# Review settings
reviews:
  # Request reviews for all pull requests
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  # Auto-approve PRs from renovate bot for dependency updates
  auto_review:
    enabled: true
    labels:
      - "renovate"
      - "dependencies"
      - "automated"
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - main
      - develop

  # Tool configurations for linting and security
  tools:
    # Python linting with ruff
    ruff:
      enabled: true

    # YAML linting
    yamllint:
      enabled: true

    # Shell script linting
    shellcheck:
      enabled: true

    # Markdown linting
    markdownlint:
      enabled: true

    # GitHub Actions workflow linting
    actionlint:
      enabled: true

    # GitHub checks integration
    github-checks:
      enabled: true

    # Secret detection
    gitleaks:
      enabled: true

    # Infrastructure as code security scanning
    checkov:
      enabled: true

    # Dockerfile linting
    hadolint:
      enabled: true

  # Path filters - what to review (exclusions use '!' prefix)
  path_filters:
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.py"
    - "**/*.j2"
    - "**/*.hcl"
    - "**/*.nomad"
    - "**/*.tf"
    - "**/*.md"
    - "**/Dockerfile"
    - "**/*.sh"
    - ".github/**"
    - "!**/*.lock"
    - "!**/package-lock.json"
    - "!**/.terraform.lock.hcl"
    - "!**/ansible.cfg"
    - "!docs/archive/**"
    - "!**/*.log"
    - "!**/*.tmp"
    - "!.venv/**"
    - "!venv/**"
    - "!__pycache__/**"

  # Review instructions specific to this project
  path_instructions:
    - path: "**/*"
      instructions: |
        Pay special attention to Ansible playbook syntax and best practices.
        Check for hardcoded secrets or credentials - all secrets should use Infisical or environment variables.
        Verify that NetBox API operations use proper error handling.
        Ensure Nomad job specifications follow HashiCorp best practices.
        Check that inventory files properly use dynamic inventory plugins.
        Validate that all playbooks use 'uv run' for execution as per CLAUDE.md.
        Ensure DNS and IPAM changes align with the implementation plan in docs/implementation/dns-ipam/.
        Verify Consul service definitions include proper health checks.
        Check that container-based deployments use appropriate resource limits.
        Ensure documentation is updated when infrastructure patterns change.

# Path grouping for better organization
path_groupings:
  - id: ansible_core
    paths:
      - "playbooks/**"
      - "inventory/**"
      - "roles/**"
    keywords:
      - ansible
      - playbook
  - id: infrastructure_code
    paths:
      - "nomad-jobs/**"
      - "**/*.hcl"
      - "**/*.tf"
    keywords:
      - nomad
      - terraform
  - id: documentation
    paths:
      - "docs/**"
      - "**/*.md"
    keywords:
      - documentation
      - readme

# Chat settings
chat:
  auto_reply: true

# Enable early access features
early_access: true

# Additional configuration for project-specific needs
custom_prompts: |
  - Prioritize security and reliability issues
  - Ensure Ansible playbooks follow best practices
  - Check for hardcoded secrets or credentials
  - Verify proper error handling in all code
  - Validate that infrastructure changes align with project patterns
