# GitLeaks configuration file
title = "Gitleaks Configuration for Andromeda Orchestration"

[extend]
# Use the default gitleaks configuration as base
useDefault = true

[[rules]]
description = "Ignore example passwords in documentation"
id = "example-passwords"
regex = '''(?i)(password|secret|key)\s*[=:]\s*["']?(changeme|example|placeholder|your-password-here)["']?'''
path = '''(?i)\.(md|rst|txt|example|template)$'''

  [rules.allowlist]
  description = "Documentation files with example passwords"
  paths = ['''docs/.*\.md$''', '''.*\.example$''', '''.*\.template$''']

[[rules]]
description = "Ignore passwords in comments"
id = "comment-passwords"
regex = '''#.*(?i)(password|secret|key)\s*[=:]\s*["']?(changeme|example)["']?'''

  [rules.allowlist]
  description = "Comments with example passwords"
  regexTarget = "line"
  regexes = ['''#.*changeme''', '''#.*example''']

# Global allowlist for known false positives
[allowlist]
description = "Global allowlist for known false positives"
paths = [
  '''nomad-jobs/platform-services/postgresql/postgresql\.nomad\.hcl''',
  '''.*\.variables\.(example|template)\.hcl$''',
  '''docs/.*\.md$''',
  '''\.claude/research-reports/.*\.md$'''
]
regexes = [
  '''token.*=.*"[a-f0-9-]{36}"''',
  '''jwt_signing.*\.b64''',
  '''example-placeholder-token''',
  '''#.*changeme''',
  '''#.*example'''
]
