# Infisical scan configuration
# This file configures secret scanning for the repository
title = "Andromeda Orchestration - Secret Scanning Configuration"

# Extend the default Infisical configuration for comprehensive coverage
[extend]
useDefault = true

# Paths to exclude from scanning
exclude_paths = [
    ".git/**",
    ".serena/cache/**",
    "reports/**",
    "*.log",
    "*.pyc",
    "__pycache__/**",
    ".venv/**",
    "venv/**",
    ".tox/**",
    ".pytest_cache/**",
    ".coverage",
    "htmlcov/**",
    "dist/**",
    "build/**",
    "*.egg-info/**"
]

# File extensions to skip
exclude_extensions = [
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".bmp",
    ".ico",
    ".pdf",
    ".zip",
    ".tar",
    ".gz",
    ".bz2",
    ".7z",
    ".rar",
    ".exe",
    ".dll",
    ".so",
    ".dylib"
]

# Global allowlist configuration
[allowlist]
description = "Andromeda Orchestration - Global allowlist for false positives"
regexTarget = "match"

# Paths to exclude from secret scanning
paths = [
    '''\.infisical-scan\.toml''',
    '''\.infisical-scan\.example\.toml''',
    '''(.*?)(jpg|gif|png|svg|doc|pdf)''',
    '''ansible\.cfg''',
    '''requirements\.yml''',
    '''molecule/.*''',
    '''\.mcp\.json''',  # MCP configuration with test UUIDs
    '''playbooks/infrastructure/consul-nomad/apply-consul-tokens-to-nomad\.yml''',  # Example tokens
    '''playbooks/infrastructure/configure-netdata-consul\.yml''',  # Example API keys
    '''playbooks/infrastructure/dns/powerdns-acl-tokens\.yml''',  # PowerDNS test tokens
    '''reports/.*\.json''',  # Report files with test data
    '''scripts/debug\.py''',  # Debug script with test UUIDs
    '''reports/consul.*\.json'''  # Consul reports with test tokens
]

# Additional patterns to allow (false positives)
# These are patterns that might look like secrets but are safe
regexes = [
    # RFC1918 private IPs
    "192\\.168\\.\\d{1,3}\\.\\d{1,3}",
    "10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}",
    "172\\.(1[6-9]|2[0-9]|3[01])\\.\\d{1,3}\\.\\d{1,3}",
    
    # Common placeholder values
    "changeme",
    "CHANGEME",
    "your-.*-here",
    "YOUR-.*-HERE",
    
    # Ansible variable references
    "\\{\\{.*\\}\\}",
    "\\$\\{.*\\}",
    
    # Consul/Nomad template references
    "\\{\\{\\s*key\\s+[\"'].*[\"']\\s*\\}\\}",
    "\\{\\{\\s*env\\s+[\"'].*[\"']\\s*\\}\\}",
    
    # Example domains
    "example\\.com",
    "localhost",
    "127\\.0\\.0\\.1",
    
    # HashiCorp service ports
    "4646",  # Nomad HTTP
    "4647",  # Nomad RPC
    "4648",  # Nomad Serf
    "8200",  # Vault HTTP
    "8201",  # Vault Cluster
    "8300",  # Consul Server RPC
    "8301",  # Consul Serf LAN
    "8302",  # Consul Serf WAN
    "8500",  # Consul HTTP
    "8501",  # Consul HTTPS
    "8600",  # Consul DNS
    
    # Test/example values
    "test-.*",
    "TEST-.*",
    "example-.*",
    "EXAMPLE-.*",
    "dummy-.*",
    "DUMMY-.*",
    "child1-api-key",  # Netdata example API key
    "child2-api-key",  # Netdata example API key
    
    # Specific test UUIDs from old commits (not real secrets)
    "d8d22964-c41e-43ab-bdba-11c063622051",  # .mcp.json test UUID
    "00b57268-c5f9-edb4-bc90-639fb4ab3232",  # consul tokens test UUID
    "aef3a19e-97f1-4b87-c4e2-8a5f4a97df7a",  # test UUID
    "be83f2fe-feb4-4e51-9a7d-7f76fd2f5e6f",  # test UUID
    "4a5b6c7d-8e9f-1a2b-3c4d-5e6f7a8b9c0d",  # test UUID
    "1a2b3c4d-5e6f-7a8b-9c0d-1a2b3c4d5e6f",  # test UUID
    "9f8e7d6c-5b4a-3c2d-1e0f-9a8b7c6d5e4f",  # test UUID
    "7e6d5c4b-3a2b-1c0d-9e8f-7a6b5c4d3e2f",  # test UUID
    "5c4b3a2b-1c0d-9e8f-7a6b-5c4d3e2f1a0b",  # test UUID
    
    # Additional test UUIDs from CI run #158
    "edf460f9-f79a-e0b8-512c-c07f57efc065",  # PowerDNS ACL tokens playbook
    "73d098e0-3dda-a9d9-e9e2-4756ee1334e4",  # Consul report UUID
    "28900e6d-6715-4ee8-9e1a-84ea086ac906",  # debug.py test UUID
    "f7bce3c8-f802-4b01-8df5-d4fea92c5bc0",  # Additional test UUID
    "a4e8d921-33e0-41a7-9e59-6f8bb1c5d3a2",  # Additional test UUID
    "9c7b4e6a-2f5d-4a8e-b3d1-7e9c8f5a3b2e",  # Additional test UUID
    "d5e9f8c7-3b2a-4e6f-9a8d-1c7b5e4f3a2d",  # Additional test UUID
    "8a7c6e5d-4b3f-2e1a-9d8c-7b6a5e4d3c2b",  # Additional test UUID
    "6b5e4d3c-2a1b-9f8e-7d6c-5a4b3e2d1c9f"   # Additional test UUID
]


# Stopwords to reduce false positives
stopwords = [
    "client",
    "server",
    "endpoint",
    "master",
    "worker",
    "agent",
    "node",
    "cluster",
    "service",
    "consul",
    "nomad",
    "vault",
    "ansible",
    "netbox",
    "infisical",
    "proxmox",
    "tailscale"
]