# markdownlint-cli2 configuration
# https://github.com/DavidAnson/markdownlint-cli2

# Define globs to include/exclude files
globs:
  - "**/*.md"
  - "!.venv/**"
  - "!venv/**"
  - "!node_modules/**"
  - "!build/**"
  - "!dist/**"
  - "!.eggs/**"
  - "!*.egg-info/**"
  - "!.pytest_cache/**"
  - "!.mypy_cache/**"
  - "!.ruff_cache/**"
  - "!__pycache__/**"
  - "!.git/**"
  - "!vendor/**"
  - "!third_party/**"
  - "!reports/**"
  - "!.claude/**"
  - "!docs/resources/ai-assistants/**"
  - "!docs/archive/**"
# Use the existing .markdownlint.json for rules
config: .markdownlint.json

# Don't fix by default (require explicit --fix flag)
fix: false
