# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - TERRAFORM
  # - SPELL # Uncomment to disable checks of spelling mistakes

DISABLE_LINTERS:
  - REPOSITORY_GITLEAKS # Too noisey, too many false positives. Already have other solutions

DISABLE_ERRORS_LINTERS:
  - ACTION_ACTIONLINT
  - ANSIBLE_ANSIBLE_LINT
  - BASH_SHELLCHECK
  - DOCKERFILE_HADOLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - YAML_YAMLLINT
  - YAML_PRETTIER
  - YAML_V8R
  - PYTHON_RUFF
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - PYTHON_BANDIT
  - PYTHON_FLAKE8
  - PYTHON_PYLINT
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - SQL_TSQLLINT


SHOW_ELAPSED_TIME: true

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
