# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - ANSIBLE_ANSIBLE_LINT
  - BASH_SHELLCHECK
  - DOCKERFILE_HADOLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - PYTHON_RUFF
  - PYTHON_MYPY
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_SEMGREP
  - REPOSITORY_KICS

DISABLE_ERRORS_LINTERS:
  - ACTION_ACTIONLINT
  - ANSIBLE_ANSIBLE_LINT
  - BASH_SHELLCHECK
  - DOCKERFILE_HADOLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - PYTHON_RUFF
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - PYTHON_BANDIT
  - PYTHON_FLAKE8
  - PYTHON_PYLINT
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_SEMGREP
  - REPOSITORY_KICS

REPOSITORY_SEMGREP_ARGUMENTS: --config=.semgrep/infrastructure-rules.yml
MARKDOWN_SUMMARY_REPORTER: true
SHOW_ELAPSED_TIME: true
SARIF_REPORTER: true
