---
# Ansible Galaxy requirements file
# Install with: ansible-galaxy install -r requirements.yml

collections:
  # General community modules
  - name: community.general
    version: ">=8.0.0"
  # Proxmox modules
  - name: community.proxmox
    version: ">=1.0.0"

  # NetBox integration (for future use)
  - name: netbox.netbox
    version: ">=3.13.0"

  # Infisical secrets management
  # Requires Python package 'infisicalsdk' on the controller/Execution Environment
  - name: infisical.vault
    version: ">=1.1.3"

  # PostgreSQL management
  - name: community.postgresql
    version: ">=4.2.0,<4.3.0"

  # Additional useful collections
  - name: ansible.posix
    version: ">=1.5.0"

  - name: ansible.utils
    version: ">=2.10.0"
    # Requires Python package 'netaddr' on the controller/Execution Environment for ipaddr filter

  # HashiCorp Vault modules (for community.hashi_vault.vault_write/read)
  # Requires Python package 'hvac' on the controller/Execution Environment
  - name: community.hashi_vault
    version: ">=6.2.0,<7.0.0"  # v7.0.0 has compatibility issues

  # Cryptography modules (for TLS/SSL certificate generation)
  - name: community.crypto
    version: ">=2.22.0"
