---
galaxy_info:
  author: andromeda-orchestration
  description: HashiCorp Vault installation and configuration
  company: Homelab
  license: MIT
  min_ansible_version: '2.15'
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - '8'
        - '9'
  galaxy_tags:
    - vault
    - hashicorp
    - secrets
    - security
    - pki
    - encryption

dependencies: []
