---
# Simple Connectivity Test for Tailscale Remote Development
# Usage:
#   uv run ansible-playbook playbooks/assessment/simple-connectivity-test.yml \
#     -i inventory/tailscale/ansible_tailscale_inventory.py \
#     --limit "tag_nomad_server,tag_nomad_client" \
#     -u ansible

- name: Simple Connectivity Testing
  hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Gather basic facts
      ansible.builtin.setup:
        gather_subset:
          - network
          - hardware

    - name: Display node information
      ansible.builtin.debug:
        msg: |
          Node: {{ inventory_hostname }}
          IP: {{ ansible_default_ipv4.address | default('Unknown') }}
          OS: {{ ansible_distribution | default('Unknown') }} {{ ansible_distribution_version | default('') }}
          Python: {{ ansible_python_version }}

    - name: Test connectivity to other nodes
      ansible.builtin.command:
        cmd: "ping -c 2 -W 2 {{ hostvars[item]['ansible_default_ipv4']['address'] | default('skip') }}"
      loop: "{{ groups['all'] }}"
      when:
        - item != inventory_hostname
        - hostvars[item]['ansible_default_ipv4'] is defined
        - hostvars[item]['ansible_default_ipv4']['address'] is defined
      register: ping_results
      changed_when: false
      failed_when: false

    - name: Display connectivity results
      ansible.builtin.debug:
        msg: |
          Connectivity from {{ inventory_hostname }}:
          {% for result in ping_results.results | default([]) %}
          {% if result.item is defined and result.rc is defined %}
          - {{ result.item }}: {{ 'SUCCESS' if result.rc == 0 else 'FAILED' }}
          {% elif result.skipped is defined and result.skipped %}
          {# Skip skipped items #}
          {% endif %}
          {% endfor %}

- name: Generate Summary Report
  hosts: all[0]
  gather_facts: false
  run_once: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Display summary
      ansible.builtin.debug:
        msg: |
          Connectivity Test Summary
          =========================
          Total nodes tested: {{ groups['all'] | length }}

          Nodes:
          {% for host in groups['all'] %}
          - {{ host }}: {{ hostvars[host]['ansible_default_ipv4']['address'] | default('No IP') }}
          {% endfor %}
