---
# Reusable task for Infisical secret lookups with proper security patterns
# Usage:
#   - name: Get Vault token
#     ansible.builtin.include_tasks: "{{ playbook_dir }}/../../../tasks/infisical-secret-lookup.yml"
#     vars:
#       secret_name: 'VAULT_PROD_ROOT_TOKEN'
#       secret_var_name: 'vault_token'
#       fallback_env_var: 'VAULT_TOKEN'  # Optional
#       infisical_path: '/apollo-13/vault'  # Optional, defaults to /apollo-13/vault
#       infisical_env: 'prod'  # Optional, defaults to prod
#       allow_empty: false  # Optional, whether to allow empty values

- name: "Validate required variables for Infisical lookup"
  ansible.builtin.assert:
    that:
      - secret_name is defined
      - secret_var_name is defined
    fail_msg: "secret_name and secret_var_name must be provided"
    quiet: true
  no_log: true
  run_once: true
  delegate_to: localhost
  tags: [secrets, infisical]

- name: "Retrieve {{ secret_name }} from Infisical"
  ansible.builtin.set_fact:
    "{{ secret_var_name }}": >-
      {%- if fallback_env_var is defined -%}
        {{ lookup('env', fallback_env_var) | default(
            lookup('infisical.vault.read_secrets',
              universal_auth_client_id=lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_ID'),
              universal_auth_client_secret=lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET'),
              project_id=infisical_project_id | default('7b832220-24c0-45bc-a5f1-ce9794a31259'),
              env_slug=infisical_env | default('prod'),
              path=infisical_path | default('/apollo-13/vault'),
              secret_name=secret_name
            ).value,
            true
          ) }}
      {%- else -%}
        {{ lookup('infisical.vault.read_secrets',
            universal_auth_client_id=lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_ID'),
            universal_auth_client_secret=lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET'),
            project_id=infisical_project_id | default('7b832220-24c0-45bc-a5f1-ce9794a31259'),
            env_slug=infisical_env | default('prod'),
            path=infisical_path | default('/apollo-13/vault'),
            secret_name=secret_name
          ).value | default('' if (allow_empty | default(false)) else omit) }}
      {%- endif -%}
    cacheable: no
  no_log: true
  run_once: true
  delegate_to: localhost
  tags: [secrets, infisical]

- name: "Validate {{ secret_name }} was retrieved"
  ansible.builtin.assert:
    that:
      - vars[secret_var_name] is defined
      - (allow_empty | default(false)) or (vars[secret_var_name] | length > 0)
    fail_msg: >-
      Failed to retrieve {{ secret_name }} from Infisical
      or environment variable {{ fallback_env_var | default('(none)') }}
    quiet: true
  no_log: true
  run_once: true
  delegate_to: localhost
  tags: [secrets, infisical]
