---
galaxy_info:
  author: basher8383
  description: Netdata monitoring agent deployment and configuration
  company: Homelab
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - focal
  galaxy_tags:
    - netdata
    - monitoring
    - observability
    - metrics
    - consul

dependencies: []
