---
# Netdata Child Node Configuration for og-homelab
# These variables apply to nodes that stream to parent nodes

# Enable streaming to parent
netdata_streaming_enabled: true
netdata_streaming_destination: "{{ groups['netdata_parents'][0] }}:19999"
netdata_streaming_api_key: "{{ vault_netdata_parent_api_key_og }}"

# Disable web interface on children to save resources
netdata_web_enabled: false

# Memory mode - use RAM for temporary storage
netdata_memory_mode: "ram"
netdata_history: 3600  # Only 1 hour of local retention

# Disable ML on children (done on parent)
netdata_ml_enabled: false

# Bind to the single network interface
netdata_bind_to: "{{ ansible_default_ipv4.address }}"

# Consul service registration
netdata_consul_enabled: true
netdata_consul_service_name: "netdata-child"
netdata_consul_service_tags:
  - "monitoring"
  - "metrics"
  - "child"
  - "streaming"
  - "og-homelab"

# Disable alarms on children (handled by parent)
netdata_alarms_enabled: false

# Disable unnecessary plugins on children (containers need fewer plugins)
netdata_plugins:
  apps: true
  cgroups: true  # Important for container monitoring
  charts.d: false
  checks: true
  diskspace: true
  ebpf: false
  fping: false
  go.d: false
  idlejitter: false
  ioping: false
  nfacct: false
  perf: false
  proc: true
  python.d: false
  slabinfo: false
  statsd: false
  tc: false  # Less important for containers
  timex: false
