---
# Clean up test services from Consul
# Usage:
# uv run ansible-playbook playbooks/infrastructure/vault/cleanup-test-services.yml -i inventory/environments/vault-cluster/production.yaml

- name: Clean Up Test Services from Consul
  hosts: vault_cluster
  gather_facts: false

  tasks:
    - name: Get node-specific token from Infisical
      set_fact:
        node_token_name: "CONSUL_TOKEN_{{ inventory_hostname | upper | replace('-', '_') }}"

    - name: Retrieve token from Infisical
      ansible.builtin.shell: |
        infisical secrets get {{ node_token_name }} --env=prod --path=/apollo-13/vault --plain
      delegate_to: localhost
      become: false
      register: consul_token_result
      environment:
        INFISICAL_UNIVERSAL_AUTH_CLIENT_ID: "{{ lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_ID') }}"
        INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET: "{{ lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET') }}"
      changed_when: false

    - name: List local services to find test services
      ansible.builtin.uri:
        url: "http://127.0.0.1:8500/v1/agent/services"
        method: GET
        headers:
          X-Consul-Token: "{{ consul_token_result.stdout }}"
        status_code: 200
      register: local_services
      become: true

    - name: Find test services
      set_fact:
        test_services: "{{ local_services.json | dict2items | selectattr('key', 'match', '^test-.*') | map(attribute='key') | list }}"

    - name: Display test services found
      ansible.builtin.debug:
        msg: "Found test services on {{ inventory_hostname }}: {{ test_services }}"
      when: test_services | length > 0

    - name: Deregister test services
      ansible.builtin.uri:
        url: "http://127.0.0.1:8500/v1/agent/service/deregister/{{ item }}"
        method: PUT
        headers:
          X-Consul-Token: "{{ consul_token_result.stdout }}"
        status_code: 200
      loop: "{{ test_services }}"
      become: true
      when: test_services | length > 0

    - name: Summary
      ansible.builtin.debug:
        msg:
          - "{{ inventory_hostname }}: Removed {{ test_services | length }} test service(s)"

- name: Verify Cleanup from Consul Server
  hosts: nomad-server-1-lloyd
  gather_facts: false

  vars:
    consul_token: "{{ lookup('env', 'CONSUL_MASTER_TOKEN') }}"

  tasks:
    - name: Set master token from environment
      set_fact:
        master_token: "{{ lookup('env', 'CONSUL_MASTER_TOKEN') }}"
      delegate_to: localhost
      become: false

    - name: Retrieve master token if not in environment
      ansible.builtin.shell: |
        infisical secrets get CONSUL_MASTER_TOKEN --env=prod --path=/apollo-13/consul --plain
      delegate_to: localhost
      become: false
      register: consul_token_result
      when: master_token == ""
      environment:
        INFISICAL_UNIVERSAL_AUTH_CLIENT_ID: "{{ lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_ID') }}"
        INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET: "{{ lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET') }}"

    - name: Set token from retrieval
      set_fact:
        consul_token: "{{ consul_token_result.stdout }}"
      when: consul_token_result.stdout is defined

    - name: Check remaining services
      ansible.builtin.shell: |
        consul catalog services -token="{{ consul_token | default(master_token) }}" | grep -E "(test-|vault)" || echo "No test services found"
      register: remaining_services
      become: true
      changed_when: false

    - name: Display final status
      ansible.builtin.debug:
        msg:
          - "✅ Test Service Cleanup Complete"
          - "Remaining relevant services:"
          - "{{ remaining_services.stdout }}"
