---
# Deploy HashiCorp Vault in Development Mode
# This playbook deploys Vault in dev mode for exploration and testing
# WARNING: Dev mode is NOT suitable for production use

- name: Deploy Vault in Development Mode
  hosts: "{{ target_hosts | default('vault_servers') }}"
  become: true
  gather_facts: true

  vars_prompt:
    - name: confirm_dev_mode
      prompt: |

        ⚠️  WARNING: Development Mode Deployment ⚠️

        This will deploy Vault in DEVELOPMENT mode with:
        - In-memory storage (data lost on restart)
        - Automatic unsealing
        - Root token: "root"
        - No TLS encryption
        - Listening on all interfaces

        This mode is for exploration and testing ONLY.

        Type 'yes' to continue
      private: false
      default: "no"

  pre_tasks:
    - name: Verify dev mode confirmation
      ansible.builtin.fail:
        msg: "Deployment cancelled. Dev mode requires explicit confirmation."
      when: confirm_dev_mode != "yes"

    - name: Display target hosts
      ansible.builtin.debug:
        msg: "Deploying Vault dev mode to: {{ ansible_hostname }} ({{ ansible_default_ipv4.address }})"

  vars:
    # Force dev mode for this playbook
    vault_mode: "dev"
    vault_dev_root_token: "root"
    vault_dev_listen_address: "0.0.0.0:8200"
    vault_ui_enabled: true
    vault_tls_disable: true
    vault_log_level: "debug"

    # Telemetry for monitoring
    vault_telemetry_enabled: true
    vault_telemetry_prometheus_retention_time: "24h"

  roles:
    - role: vault
      tags:
        - vault

  post_tasks:
    - name: Wait for Vault to start
      ansible.builtin.wait_for:
        port: "{{ vault_port }}"
        host: "{{ ansible_default_ipv4.address }}"
        delay: 5
        timeout: 30
        state: started

    - name: Check Vault status
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}:{{ vault_port }}/v1/sys/health"
        method: GET
        status_code: [200, 429, 472, 473, 501, 503]
      register: vault_health

    - name: Display Vault health status
      ansible.builtin.debug:
        var: vault_health.json

    - name: Create basic test secret
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}:{{ vault_port }}/v1/secret/data/test"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_dev_root_token }}"
        body_format: json
        body:
          data:
            message: "Vault dev mode is working!"
            deployed_at: "{{ ansible_date_time.iso8601 }}"
            deployed_by: "{{ ansible_user_id }}"
        status_code: [200, 204]
      register: test_secret

    - name: Display access information
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Vault Development Mode Successfully Deployed!"
          - "=========================================="
          - ""
          - "Access Information:"
          - "  UI URL: http://{{ ansible_default_ipv4.address }}:{{ vault_port }}/ui"
          - "  API URL: http://{{ ansible_default_ipv4.address }}:{{ vault_port }}"
          - "  Root Token: {{ vault_dev_root_token }}"
          - ""
          - "CLI Access:"
          - "  export VAULT_ADDR='http://{{ ansible_default_ipv4.address }}:{{ vault_port }}'"
          - "  export VAULT_TOKEN='{{ vault_dev_root_token }}'"
          - "  vault status"
          - ""
          - "Test the deployment:"
          - "  vault kv get secret/test"
          - ""
          - "Consul Integration (if available):"
          - "  Service registered as: vault.service.consul"
          - ""
          - "⚠️  REMINDER: This is DEVELOPMENT mode only!"
          - "=========================================="

    - name: Register with Consul (if available)
      ansible.builtin.include_role:
        name: consul
        tasks_from: register_service
      vars:
        consul_service:
          name: vault
          port: "{{ vault_port }}"
          tags:
            - vault
            - dev
          checks:
            - name: "Vault HTTP"
              http: "http://{{ ansible_default_ipv4.address }}:{{ vault_port }}/v1/sys/health"
              interval: "10s"
              timeout: "5s"
      when: "'consul' in group_names or consul_agent_enabled | default(false)"
      tags:
        - consul-register
