---
# Final verification of Vault service registration in Consul
# Usage:
# uv run ansible-playbook playbooks/infrastructure/vault/final-vault-consul-verification.yml -i inventory/environments/doggos-homelab/proxmox.yml

- name: Final Verification of Vault Service Registration
  hosts: nomad-server-1-lloyd
  gather_facts: false

  pre_tasks:
    - name: Retrieve Consul master token securely
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../../../tasks/infisical-secret-lookup.yml"
      vars:
        secret_name: 'CONSUL_MASTER_TOKEN'
        secret_var_name: 'consul_token'
        fallback_env_var: 'CONSUL_MASTER_TOKEN'
        infisical_path: '/apollo-13/consul'
      tags: [secrets]

  tasks:
    - name: Verify master token is set
      ansible.builtin.assert:
        that:
          - consul_token != ""
        fail_msg: 'Failed to retrieve CONSUL_MASTER_TOKEN from Infisical'
        success_msg: 'Master token verified'

    - name: Check all services in catalog
      ansible.builtin.shell: |
        consul catalog services -token="{{ consul_token }}"
      register: all_services
      changed_when: false
      become: true

    - name: Check Vault service nodes
      ansible.builtin.shell: |
        consul catalog nodes -service=vault -token="{{ consul_token }}"
      register: vault_nodes
      changed_when: false
      become: true

    - name: Check Vault service health via API
      ansible.builtin.uri:
        url: 'http://127.0.0.1:8500/v1/health/service/vault'
        method: GET
        headers:
          X-Consul-Token: '{{ consul_token }}'
        status_code: 200
      register: vault_health
      become: true

    - name: Parse health check status
      set_fact:
        health_summary: |
          {% set ns = namespace(passing=0, warning=0, critical=0) %}
          {% for node in vault_health.json %}
            {% for check in node.Checks %}
              {% if check.Status == 'passing' %}
                {% set ns.passing = ns.passing + 1 %}
              {% elif check.Status == 'warning' %}
                {% set ns.warning = ns.warning + 1 %}
              {% else %}
                {% set ns.critical = ns.critical + 1 %}
              {% endif %}
            {% endfor %}
          {% endfor %}
          Passing: {{ ns.passing }}, Warning: {{ ns.warning }}, Critical: {{ ns.critical }}

    - name: Display comprehensive results
      ansible.builtin.debug:
        msg:
          - '✅ ==================== VAULT CONSUL INTEGRATION COMPLETE ===================='
          - ''
          - '📋 All Services in Catalog:'
          - '{{ all_services.stdout_lines }}'
          - ''
          - '🔐 Vault Service Nodes ({{ vault_nodes.stdout_lines | length }} total):'
          - '{{ vault_nodes.stdout }}'
          - ''
          - '❤️ Health Check Status:'
          - '{{ health_summary }}'
          - ''
          - '============================================================================='
          - ''
          - '🎉 SUCCESS: All 4 Vault nodes are registered in Consul!'
          - 'Note: Health checks may show as critical if Vault services are not running.'
          - 'This is expected in a development/testing environment.'
