---
# Manage secrets in Vault
# This playbook safely checks and manages secrets in Vault

- name: Manage Vault Secrets
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    # Vault configuration from environment (set via direnv/.envrc)
    vault_addr: "{{ ansible_env.VAULT_ADDR | default('http://192.168.10.11:8200') }}"
    vault_token: '{{ ansible_env.VAULT_TOKEN }}'
  tasks:
    - name: Check Vault status
      community.hashi_vault.vault_read:
        url: '{{ vault_addr }}'
        auth_method: token
        token: '{{ vault_token }}'
        path: sys/health
      register: vault_health

    - name: Display Vault health
      debug:
        msg: |
          Vault Status:
          - Initialized: {{ vault_health.data.initialized }}
          - Sealed: {{ vault_health.data.sealed }}
          - Version: {{ vault_health.data.version }}

    - name: List mounted secrets engines
      community.hashi_vault.vault_read:
        url: '{{ vault_addr }}'
        auth_method: token
        token: '{{ vault_token }}'
        path: sys/mounts
      register: mounts

    - name: Display available secrets engines
      debug:
        var: mounts.data

    - name: Check for KV engines at common paths
      set_fact:
        kv_v1_exists: "{{ 'kv/' in mounts.data }}"
        kv_v2_secret_exists: "{{ 'secret/' in mounts.data and mounts.data['secret/'].type == 'kv' }}"
        kv_v2_version: "{{ mounts.data['secret/'].options.version | default('1') if 'secret/' in mounts.data and mounts.data['secret/'].type == 'kv' else 'not_kv' }}"

    - name: Set primary KV engine facts
      set_fact:
        primary_kv_path: "{{ 'secret/' if kv_v2_secret_exists else ('kv/' if kv_v1_exists else 'none') }}"
        primary_kv_version: "{{ kv_v2_version if kv_v2_secret_exists else ('1' if kv_v1_exists else 'none') }}"
        kv_exists: '{{ kv_v1_exists or kv_v2_secret_exists }}'

    - name: Display KV engine status
      debug:
        msg: |
          KV Engine Status:
          - Primary KV path: {{ primary_kv_path }}
          - KV version: {{ primary_kv_version }}
          - KV v1 at 'kv/': {{ 'Yes' if kv_v1_exists else 'No' }}
          - KV v2 at 'secret/': {{ 'Yes (v' + kv_v2_version + ')' if kv_v2_secret_exists else 'No' }}

    - name: List existing secrets in primary KV engine
      community.hashi_vault.vault_list:
        url: '{{ vault_addr }}'
        auth_method: token
        token: '{{ vault_token }}'
        path: "{{ primary_kv_path | regex_replace('/$', '') }}{{ '/metadata' if primary_kv_version == '2' else '' }}"
      register: kv_secrets
      when: kv_exists and primary_kv_path != 'none'
      failed_when: false

    - name: Debug kv_secrets structure
      debug:
        var: kv_secrets
      when: kv_exists and primary_kv_path != 'none'

    - name: Display existing secrets
      debug:
        msg: |
          Existing secrets in {{ primary_kv_path }} (KV v{{ primary_kv_version }}):
          {% if kv_secrets.data is defined %}
          - Vault returned data: {{ 'Yes' if kv_secrets.data else 'No data' }}
          {% else %}
          - No secrets found or unable to list (skipped: {{ kv_secrets.skipped | default('false') }})
          {% endif %}
      when: kv_exists and primary_kv_path != 'none'

    - name: Check for PowerDNS secrets
      community.hashi_vault.vault_read:
        url: '{{ vault_addr }}'
        auth_method: token
        token: '{{ vault_token }}'
        path: "{{ primary_kv_path | regex_replace('/$', '') }}{{ '/data' if primary_kv_version == '2' else '' }}/pdns"
      register: pdns_secrets
      failed_when: false
      when: kv_exists and primary_kv_path != 'none'

    - name: Display PowerDNS secrets status
      debug:
        msg: |
          PowerDNS secrets in {{ primary_kv_path }}pdns:
          {% if pdns_secrets.data is defined %}
          {% if primary_kv_version == '2' and pdns_secrets.data.data is defined %}
          Exists with keys: {{ pdns_secrets.data.data.keys() | list }}
          {% elif primary_kv_version == '1' %}
          Exists with keys: {{ pdns_secrets.data.keys() | list }}
          {% else %}
          Exists but unable to parse keys
          {% endif %}
          {% else %}
          Not found
          {% endif %}
      when: kv_exists and primary_kv_path != 'none'

    - name: Check for PostgreSQL secrets
      community.hashi_vault.vault_read:
        url: '{{ vault_addr }}'
        auth_method: token
        token: '{{ vault_token }}'
        path: "{{ primary_kv_path | regex_replace('/$', '') }}{{ '/data' if primary_kv_version == '2' else '' }}/postgres"
      register: postgres_secrets
      failed_when: false
      when: kv_exists and primary_kv_path != 'none'

    - name: Display PostgreSQL secrets status
      debug:
        msg: |
          PostgreSQL secrets in {{ primary_kv_path }}postgres:
          {% if postgres_secrets.data is defined %}
          {% if primary_kv_version == '2' and postgres_secrets.data.data is defined %}
          Exists with keys: {{ postgres_secrets.data.data.keys() | list }}
          {% elif primary_kv_version == '1' %}
          Exists with keys: {{ postgres_secrets.data.keys() | list }}
          {% else %}
          Exists but unable to parse keys
          {% endif %}
          {% else %}
          Not found
          {% endif %}
      when: kv_exists and primary_kv_path != 'none'
