---
# Update Consul ACL policy for Vault clients
# Usage: uv run ansible-playbook playbooks/infrastructure/vault/update-consul-acl-policy.yml
#        -i inventory/environments/doggos-homelab/proxmox.yml

- name: Update Consul ACL Policy for Vault Clients
  hosts: nomad-server-1-lloyd
  gather_facts: false

  pre_tasks:
    - name: Retrieve Consul master token securely
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../../../tasks/infisical-secret-lookup.yml"
      vars:
        secret_name: 'CONSUL_MASTER_TOKEN'
        secret_var_name: 'consul_master_token'
        fallback_env_var: 'CONSUL_MASTER_TOKEN'
        infisical_path: '/apollo-13/consul'
      tags: [secrets]

  vars:
    policy_name: 'vault-client-policy'
    consul_addr: 'http://127.0.0.1:8500'

  tasks:
    - name: Verify master token is set
      ansible.builtin.assert:
        that:
          - consul_master_token != ""
        fail_msg: 'Failed to retrieve CONSUL_MASTER_TOKEN from Infisical'
        success_msg: 'Master token verified'

    - name: Copy updated Vault client ACL policy file
      ansible.builtin.copy:
        src: '{{ playbook_dir }}/../../../roles/consul/files/policies/vault-client.hcl'
        dest: /tmp/vault-client-policy.hcl
        mode: '0600'
      become: true

    - name: Read policy rules
      ansible.builtin.slurp:
        src: /tmp/vault-client-policy.hcl
      register: policy_rules
      become: true

    - name: Upsert Vault client ACL policy
      ansible.builtin.uri:
        url: "{{ (consul_use_tls | default(false)) | ternary('https://127.0.0.1:8501', 'http://127.0.0.1:8500') }}/v1/acl/policy"
        method: PUT
        headers:
          X-Consul-Token: "{{ consul_master_token }}"
        body_format: json
        validate_certs: "{{ consul_validate_certs | default(true) }}"
        body:
          Name: "{{ policy_name }}"
          Description: "Policy for Vault Consul client agents (updated)"
          Rules: "{{ policy_rules.content | b64decode }}"
        status_code: [200]
      register: policy_update
      become: true
      no_log: true
    - name: Display policy update result
      ansible.builtin.debug:
        msg:
          - "✅ Policy '{{ policy_name }}' has been updated"
          - "Status: {{ policy_update.status }}"
          - "Response: {{ policy_update.json | default('Success') }}"

    - name: Clean up policy file
      ansible.builtin.file:
        path: /tmp/vault-client-policy.hcl
        state: absent
      become: true

    - name: Display next steps
      ansible.builtin.debug:
        msg:
          - '✅ ACL Policy updated successfully!'
          - ''
          - "The tokens don't need to be regenerated - the existing tokens"
          - 'will automatically use the updated policy permissions.'
          - ''
          - 'Next: Run the fix-vault-service-registration playbook to apply the service configuration.'
