---
# Update Consul ACL policy for Vault clients
# See: playbooks/infrastructure/README.md#consul-configuration

- name: Update Consul ACL Policy for Vault Clients
  hosts: nomad-server-1-lloyd
  gather_facts: false

  pre_tasks:
    - name: Retrieve Consul master token securely
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../../../tasks/infisical-secret-lookup.yml"
      vars:
        secret_name: 'CONSUL_MASTER_TOKEN'
        secret_var_name: 'consul_master_token'
        fallback_env_var: 'CONSUL_MASTER_TOKEN'
        infisical_path: '/apollo-13/consul'
      tags: [secrets]

  vars:
    policy_name: 'vault-client-policy'

  tasks:
    - name: Verify master token is set
      ansible.builtin.assert:
        that:
          - consul_master_token != ""
        fail_msg: 'Failed to retrieve CONSUL_MASTER_TOKEN from Infisical'
        success_msg: 'Master token verified'

    - name: Copy updated Vault client ACL policy file
      ansible.builtin.copy:
        src: '{{ playbook_dir }}/../../../roles/consul/files/policies/vault-client.hcl'
        dest: /tmp/vault-client-policy.hcl
        mode: '0600'
      become: true

    - name: Load policy file content from controller
      ansible.builtin.set_fact:
        policy_rules_raw: "{{ lookup('file', playbook_dir ~ '/../../../roles/consul/files/policies/vault-client.hcl') }}"
        cacheable: no
    - name: Upsert Vault client ACL policy
      ansible.builtin.uri:
        url: "{{ consul_base_url }}/v1/acl/policy"
        method: PUT
        headers:
          X-Consul-Token: "{{ consul_master_token }}"
        body_format: json
        validate_certs: "{{ consul_validate_certs }}"
        ca_path: "{{ consul_ca_path | default(omit) }}"
        timeout: "{{ consul_http_timeout | default(15) }}"
        body:
          Name: "{{ policy_name }}"
          Description: "Policy for Vault Consul client agents (updated)"
          Rules: "{{ policy_content.content | b64decode }}"
        status_code: [200, 201]
      register: policy_update
      become: true
      no_log: true
      retries: 5
      delay: 3
      until: policy_update is succeeded and policy_update.status in [200, 201]

    - name: Display policy update result
      ansible.builtin.debug:
        msg:
          - "✅ Policy '{{ policy_name }}' has been updated successfully"
          - "Status: {{ policy_update.status }} ({{ policy_update.status_text | default('OK') }})"
          - "Response contains sensitive policy data - not displayed for security"

    - name: Clean up policy file
      ansible.builtin.file:
        path: /tmp/vault-client-policy.hcl
        state: absent
      become: true

    - name: Display next steps
      ansible.builtin.debug:
        msg:
          - '✅ ACL Policy updated successfully!'
          - ''
          - "The tokens don't need to be regenerated - the existing tokens"
          - 'will automatically use the updated policy permissions.'
          - ''
          - 'Next: Run the fix-vault-service-registration playbook to apply the service configuration.'
