---
# Update Netdata streaming configuration for mesh topology

- name: Update streaming on doggos-homelab parents
  hosts: lloyd,holly,mable
  become: true
  gather_facts: true

  tasks:
    - name: Update stream.conf for mesh topology
      ansible.builtin.copy:
        content: |
          # Netdata streaming configuration
          # This file controls streaming and replication

          [stream]
              # Enable streaming to other parents (mesh topology)
              enabled = yes

              # Destination list with all other parent nodes
              {% set parents = [] %}
              {% if 'lloyd' != inventory_hostname %}
              {%   set _ = parents.append('192.168.10.11:19999') %}
              {% endif %}
              {% if 'holly' != inventory_hostname %}
              {%   set _ = parents.append('192.168.10.12:19999') %}
              {% endif %}
              {% if 'mable' != inventory_hostname %}
              {%   set _ = parents.append('192.168.10.13:19999') %}
              {% endif %}
              {# Always add og-homelab parent #}
              {% set _ = parents.append('192.168.30.50:19999') %}
              destination = {{ parents | join(' ') }}

              # Mesh replication API key
              api key = netdata-parent-mesh-key

              # Streaming configuration
              default memory mode = dbengine
              health enabled by default = auto
              default postpone alarms on connect seconds = 60
              reconnect delay seconds = 5
              initial clock resync iterations = 2
              send charts matching = *
              enable compression = yes

          # API keys for accepting streams
          # Child nodes streaming
          [{{ vault_netdata_parent_api_key | default('doggos-child-key') }}]
              enabled = yes
              default history = 3600
              default memory mode = dbengine
              health enabled by default = auto
              allow from = 192.168.11.0/24
              default postpone alarms on connect seconds = 60
              multiple connections = allow

          # Parent mesh replication
          [netdata-parent-mesh-key]
              enabled = yes
              default history = 3600
              default memory mode = dbengine
              health enabled by default = auto
              allow from = 192.168.10.0/24 192.168.30.0/24
              default postpone alarms on connect seconds = 60
              multiple connections = allow
        dest: /etc/netdata/stream.conf
        owner: netdata
        group: netdata
        mode: '0640'
        backup: true

    - name: Restart netdata
      ansible.builtin.systemd:
        name: netdata
        state: restarted
        daemon_reload: true

- name: Update streaming on og-homelab parent
  hosts: pve1
  become: true
  gather_facts: true

  tasks:
    - name: Update stream.conf for mesh topology
      ansible.builtin.copy:
        content: |
          # Netdata streaming configuration
          # This file controls streaming and replication

          [stream]
              # Enable streaming to other parents (mesh topology)
              enabled = yes

              # Destination list with all doggos parents
              destination = 192.168.10.11:19999 192.168.10.12:19999 192.168.10.13:19999

              # Mesh replication API key
              api key = netdata-parent-mesh-key

              # Streaming configuration
              default memory mode = dbengine
              health enabled by default = auto
              default postpone alarms on connect seconds = 60
              reconnect delay seconds = 5
              initial clock resync iterations = 2
              send charts matching = *
              enable compression = yes

          # API keys for accepting streams
          # Child nodes streaming
          [{{ vault_netdata_parent_api_key_og | default('og-child-key') }}]
              enabled = yes
              default history = 3600
              default memory mode = dbengine
              health enabled by default = auto
              allow from = 192.168.30.0/24
              default postpone alarms on connect seconds = 60
              multiple connections = allow

          # Parent mesh replication
          [netdata-parent-mesh-key]
              enabled = yes
              default history = 3600
              default memory mode = dbengine
              health enabled by default = auto
              allow from = 192.168.10.0/24 192.168.30.0/24
              default postpone alarms on connect seconds = 60
              multiple connections = allow
        dest: /etc/netdata/stream.conf
        owner: netdata
        group: netdata
        mode: '0640'
        backup: true

    - name: Restart netdata
      ansible.builtin.systemd:
        name: netdata
        state: restarted
        daemon_reload: true

- name: Verify mesh connectivity
  hosts: lloyd,holly,mable,pve1
  become: true
  gather_facts: false

  tasks:
    - name: Wait for services to stabilize
      ansible.builtin.pause:
        seconds: 10

    - name: Check streaming connections
      ansible.builtin.shell: |
        ss -tan | grep :19999 | grep ESTAB | wc -l
      register: connection_count
      changed_when: false

    - name: Display mesh status
      ansible.builtin.debug:
        msg:
          - 'Node: {{ inventory_hostname }}'
          - 'Active connections: {{ connection_count.stdout }}'
          - 'Expected: 3+ (children) + 3 (mesh peers)'
