---
# Default variables for all groups
# These are primarily used for CI/CD testing and can be overridden per environment

# Domain configuration (required for domain-assertions.yml)
homelab_domain: "example.com"  # Override with actual domain in inventory
cluster_subdomain: "homelab"   # Override with actual subdomain in inventory
fqdn_suffix: "{{ cluster_subdomain }}.{{ homelab_domain }}"  # Composite FQDN for centralized domain usage

# Common infrastructure settings
ansible_python_interpreter: /usr/bin/python3

# Default network settings
default_interface: "{{ ansible_default_ipv4.interface | default('eth0') }}"
default_ipv4: "{{ ansible_default_ipv4.address | default('127.0.0.1') }}"

# Service ports (common across clusters)
consul_port: 8500
nomad_port: 4646
vault_port: 8200

# Consul configuration
consul_scheme: "http"  # Override to "https" for TLS-enabled deployments
consul_base_url: "{{ consul_scheme }}://127.0.0.1:{{ consul_port }}"
consul_validate_certs: true  # Set to false for self-signed certificates

# Consul binary download configuration
consul_version: "1.21.4"  # Update to latest stable version from https://releases.hashicorp.com/consul/
consul_arch: "linux_amd64"  # Override for different architectures (linux_arm64, darwin_amd64, etc.)
consul_zip_sha256: "a641502dc2bd28e1ed72d3d48a0e8b98c83104d827cf33bee2aed198c0b849df"
# SHA256 for Consul 1.21.4 linux_amd64
# To update: curl -s "https://releases.hashicorp.com/consul/${consul_version}/consul_${consul_version}_SHA256SUMS" \
#   | grep ${consul_arch} | awk '{print $1}'

# Common tags and metadata
deployment_environment: "development"  # Note: 'environment' is reserved in Ansible
managed_by: "ansible"

# Timeouts and retries
default_timeout: 30
default_retries: 3
