---
# Enable ACLs on Consul client agents
# Usage: uv run ansible-playbook playbooks/infrastructure/consul/enable-client-acls.yml -i inventory/doggos-homelab/infisical.proxmox.yml

- name: Enable ACLs on Consul Clients
  hosts: tag_client
  become: true
  vars:
    consul_client_token: "[REDACTED_NOMAD_TOKEN]"

  tasks:
    - name: Add ACL configuration to Consul
      ansible.builtin.blockinfile:
        path: /etc/consul.d/consul.hcl
        marker: "# {mark} ANSIBLE MANAGED ACL CONFIGURATION"
        block: |
          # ACL Configuration
          acl {
            enabled = true
            default_policy = "allow"
            enable_token_persistence = true
            tokens {
              agent = "{{ consul_client_token }}"
              default = "{{ consul_client_token }}"
            }
          }
        state: present
      register: config_updated

    - name: Restart Consul service
      ansible.builtin.systemd:
        name: consul
        state: restarted
        daemon_reload: true
      when: config_updated.changed

    - name: Wait for Consul to be ready
      ansible.builtin.wait_for:
        port: 8500
        host: "127.0.0.1"
        delay: 5
        timeout: 30
      when: config_updated.changed

- name: Verify Configuration
  hosts: nomad-server-1-lloyd

  tasks:
    - name: Wait for agents to reconnect
      ansible.builtin.pause:
        seconds: 10

    - name: Check Consul members
      ansible.builtin.command: consul members
      register: members_status
      changed_when: false

    - name: Display status
      ansible.builtin.debug:
        msg:
          - "Consul client ACLs enabled!"
          - ""
          - "Consul members:"
          - "{{ members_status.stdout_lines }}"
