---
# Enable Consul Telemetry on all nodes
# This playbook enables the Prometheus metrics endpoint in Consul

- name: Enable Consul telemetry across all nodes
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Enable telemetry in Consul configuration
      include_role:
        name: consul
        tasks_from: telemetry
      vars:
        consul_prometheus_retention_time: "{{ prometheus_retention_time | default('360h') }}"

    - name: Verify telemetry endpoint is accessible
      uri:
        url: 'http://127.0.0.1:8500/v1/agent/metrics?format=prometheus'
        validate_certs: false
      register: metrics_check
      failed_when: false
      changed_when: false
      retries: 3
      delay: 5

    - name: Report telemetry status
      debug:
        msg: "Consul telemetry endpoint {{ 'enabled' if metrics_check.status == 200 else 'not accessible' }} on {{ inventory_hostname }}"

- name: Summary report
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Generate telemetry status report
      debug:
        msg: |
          Consul Telemetry Status:
          {% for host in groups['all'] %}
          - {{ host }}: {{ hostvars[host]['metrics_check']['status'] | default('unknown') }}
          {% endfor %}
