---
# Sync DNS zones and records from NetBox to PowerDNS
- name: Sync NetBox DNS to PowerDNS
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    netbox_url: "https://192.168.30.213"
    powerdns_api_url: "http://192.168.11.21:21421/api/v1"  # Dynamic port on nomad-client-2
    powerdns_api_key: "changeme789xyz"  # From job configuration
    infisical_project_id: "7b832220-24c0-45bc-a5f1-ce9794a31259"
    infisical_env: "{{ lookup('env', 'INFISICAL_ENV') | default('prod') }}"

  tasks:
    - name: Retrieve NetBox API token from Infisical
      set_fact:
        netbox_token: >-
          {{ (lookup('infisical.vault.read_secrets',
                     universal_auth_client_id=lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_ID'),
                     universal_auth_client_secret=lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET'),
                     project_id=infisical_project_id,
                     env_slug=infisical_env,
                     path='/apollo-13/services/netbox',
                     secret_name='NETBOX_API_KEY')).value }}
      no_log: true

    - name: Get DNS zones from NetBox
      uri:
        url: "{{ netbox_url }}/api/plugins/netbox-dns/zones/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        validate_certs: false
      register: netbox_zones

    - name: Get DNS records from NetBox
      uri:
        url: "{{ netbox_url }}/api/plugins/netbox-dns/records/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        validate_certs: false
      register: netbox_records

    - name: Check PowerDNS API connectivity
      uri:
        url: "{{ powerdns_api_url }}/servers/localhost"
        method: GET
        headers:
          X-API-Key: "{{ powerdns_api_key }}"
      register: pdns_status

    - name: Create zones in PowerDNS
      uri:
        url: "{{ powerdns_api_url }}/servers/localhost/zones"
        method: POST
        headers:
          X-API-Key: "{{ powerdns_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ item.name }}."
          kind: "Native"
          masters: []
          nameservers: 
            - "ns1.homelab.local."
          rrsets:
            - name: "{{ item.name }}."
              type: "SOA"
              records:
                - content: "{{ item.soa_mname.name }} {{ item.soa_rname }} {{ item.soa_serial }} {{ item.soa_refresh }} {{ item.soa_retry }} {{ item.soa_expire }} {{ item.soa_minimum }}"
                  disabled: false
              ttl: "{{ item.soa_ttl }}"
        status_code: [201, 204, 409]
      loop: "{{ netbox_zones.json.results }}"
      when: netbox_zones.json.count > 0
      register: zone_creation
      failed_when: zone_creation.status not in [201, 204, 409]

    - name: Add A records to PowerDNS
      uri:
        url: "{{ powerdns_api_url }}/servers/localhost/zones/{{ item.zone.name }}."
        method: PATCH
        headers:
          X-API-Key: "{{ powerdns_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          rrsets:
            - name: "{{ item.fqdn }}"
              type: "{{ item.type }}"
              changetype: "REPLACE"
              records:
                - content: "{{ item.value }}"
                  disabled: false
              ttl: "{{ item.ttl | default(3600) }}"
      loop: "{{ netbox_records.json.results | selectattr('type', 'equalto', 'A') | list }}"
      when: 
        - netbox_records.json.count > 0
        - item.type == 'A'
      register: record_creation

    - name: Add NS records to PowerDNS
      uri:
        url: "{{ powerdns_api_url }}/servers/localhost/zones/{{ item.zone.name }}."
        method: PATCH
        headers:
          X-API-Key: "{{ powerdns_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          rrsets:
            - name: "{{ item.fqdn }}"
              type: "{{ item.type }}"
              changetype: "REPLACE"
              records:
                - content: "{{ item.value }}."
                  disabled: false
              ttl: "{{ item.ttl | default(3600) }}"
      loop: "{{ netbox_records.json.results | selectattr('type', 'equalto', 'NS') | list }}"
      when: 
        - netbox_records.json.count > 0
        - item.type == 'NS'

    - name: Display sync summary
      debug:
        msg:
          - "DNS Sync Complete!"
          - "Zones synced: {{ netbox_zones.json.count }}"
          - "Records processed: {{ netbox_records.json.count }}"
          - ""
          - "PowerDNS API: {{ powerdns_api_url }}"
          - ""
          - "Test with:"
          - "  dig @192.168.11.20 ns1.homelab.local"
          - "  dig @192.168.11.20 homelab.local SOA"