---
# Update nftables rules for Nomad clients to support both static and dynamic ports

- name: Update nftables for Nomad workloads
  hosts: tag_client
  become: true

  tasks:
    - name: Create Nomad-friendly nftables configuration
      template:
        src: nftables-nomad-client.conf.j2
        dest: /etc/nftables.conf
        owner: root
        group: root
        mode: '0755'
        backup: true
      notify: restart nftables

  handlers:
    - name: restart nftables
      systemd:
        name: nftables
        state: restarted

- name: Verify nftables rules
  hosts: tag_client
  become: true

  tasks:
    - name: Check nftables status
      command: nft list ruleset
      register: nft_rules
      changed_when: false

    - name: Verify PowerDNS ports are allowed
      assert:
        that:
          - "'dport 53' in nft_rules.stdout"
          - "'dport 8081' in nft_rules.stdout"
          - "'20000-32000' in nft_rules.stdout"
        fail_msg: 'Required ports not found in nftables rules'
        success_msg: 'All required ports are configured'
