---
# Host variables for Vault production node 1 (holly)
# Production cluster member with auto-unseal

ansible_host: 192.168.10.31
ansible_user: ansible

# Vault configuration
vault_role: production
vault_node_id: vault-prod-1
vault_cluster_name: 'vault-production'
vault_datacenter: 'doggos-cluster'

# Auto-unseal configuration (points to master)
vault_auto_unseal_enabled: true
vault_auto_unseal_type: 'transit'
vault_auto_unseal_config:
  address: 'http://{{ hostvars["vault-master-lloyd"]["ansible_host"] }}:8200'  # Master vault (derived from inventory)
  token: "{{ lookup('infisical.vault.read_secrets',
    universal_auth_client_id=lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_ID'),
    universal_auth_client_secret=lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET'),
    project_id='7b832220-24c0-45bc-a5f1-ce9794a31259',
    env_slug='prod',
    path='/apollo-13/vault',
    secret_name='VAULT_TRANSIT_TOKEN').value }}"
  disable_renewal: false
  key_name: 'autounseal'
  mount_path: 'transit/'

# Proxmox VM configuration
proxmox_node: holly
vm_id: 3201
vm_memory: 2048
vm_cores: 2
vm_storage: 20

# Network configuration
vault_bind_addr: '0.0.0.0'
vault_cluster_addr: 'http://{{ ansible_default_ipv4.address }}:8201'
vault_api_addr: 'http://{{ ansible_default_ipv4.address }}:8200'

# Raft storage configuration
vault_storage_backend: 'raft'
vault_raft_node_id: 'vault-prod-1'
vault_raft_retry_join: []  # Production cluster forms its own raft initially

# Storage configuration
vault_data_dir: '/opt/vault/data'
vault_config_dir: '/etc/vault.d'
vault_log_dir: '/var/log/vault'
vault_user: 'vault'
vault_group: 'vault'

# Performance and resource limits
vault_max_lease_ttl: '768h'
vault_default_lease_ttl: '168h'
vault_log_level: 'INFO'
vault_disable_cache: false
vault_disable_mlock: false

# Audit configuration
vault_audit_enabled: true
vault_audit_file_path: '/var/log/vault/audit.log'

# UI and telemetry
vault_ui_enabled: true
vault_telemetry_enabled: true
