---
# Service Endpoints Configuration
# Central definition of service endpoints to avoid hardcoded IPs
# These can be overridden by environment variables or inventory-specific configurations

# HashiCorp Service Endpoints
service_endpoints:
  # Consul service endpoint
  consul:
    addr: "{{ lookup('env', 'CONSUL_HTTP_ADDR') | default('http://consul.service.consul:8500', true) }}"
    description: "Consul HTTP API endpoint"

  # Nomad service endpoint
  nomad:
    addr: "{{ lookup('env', 'NOMAD_ADDR') | default('http://nomad.service.consul:4646', true) }}"
    description: "Nomad HTTP API endpoint"

  # Vault service endpoint
  vault:
    addr: "{{ lookup('env', 'VAULT_ADDR') | default('http://vault.service.consul:8200', true) }}"
    description: "Vault HTTP API endpoint"

  # Alternative: Direct IP-based endpoints (for environments without service discovery)
  consul_direct:
    addr: "{{ lookup('env', 'CONSUL_HTTP_ADDR') | default(omit) }}"
    description: "Consul direct IP endpoint (fallback)"

  nomad_direct:
    addr: "{{ lookup('env', 'NOMAD_ADDR') | default(omit) }}"
    description: "Nomad direct IP endpoint (fallback)"

  vault_direct:
    addr: "{{ lookup('env', 'VAULT_ADDR') | default(omit) }}"
    description: "Vault direct IP endpoint (fallback)"
