---
# Molecule configuration for testing Ansible roles
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance-ubuntu
    image: ubuntu:22.04
    pre_build_image: false
    dockerfile: Dockerfile
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined

  - name: instance-debian
    image: debian:12
    pre_build_image: false
    dockerfile: Dockerfile
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      stdout_callback: yaml
      verbosity: 1
  inventory:
    host_vars:
      instance-ubuntu:
        ansible_python_interpreter: /usr/bin/python3
      instance-debian:
        ansible_python_interpreter: /usr/bin/python3
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_COLLECTIONS_PATH: "~/.ansible/collections:/usr/share/ansible/collections"

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
