---
# Remove port 80 and 443 from reserved ports on Nomad clients
# This allows Traefik to bind to these ports
# Usage: uv run ansible-playbook playbooks/infrastructure/nomad/unreserve-lb-ports.yml -i inventory/doggos-homelab/infisical.proxmox.yml

- name: Unreserve Load Balancer Ports on Nomad Clients
  hosts: tag_client
  become: true
  vars:
    nomad_config_file: /etc/nomad.d/nomad.hcl

  tasks:
    - name: Update reserved ports to only include SSH (22)
      ansible.builtin.replace:
        path: '{{ nomad_config_file }}'
        regexp: 'reserved_ports = "22,80,443"'
        replace: 'reserved_ports = "22"'
      register: config_updated

    - name: Restart Nomad client if configuration changed
      ansible.builtin.systemd:
        name: nomad
        state: restarted
        daemon_reload: true
      when: config_updated.changed

    - name: Wait for Nomad to be ready
      ansible.builtin.wait_for:
        port: 4646
        host: '{{ ansible_default_ipv4.address }}'
        delay: 5
        timeout: 30
      when: config_updated.changed

- name: Verify Configuration
  hosts: nomad-server-1-lloyd

  tasks:
    - name: Check node status
      ansible.builtin.command: nomad node status
      register: node_status
      changed_when: false

    - name: Display status
      ansible.builtin.debug:
        msg:
          - 'Ports 80 and 443 are now available for Traefik!'
          - ''
          - 'Node status:'
          - '{{ node_status.stdout_lines }}'
          - ''
          - 'You can now deploy Traefik successfully.'
