---
# Re-enable service identity requirement in Nomad
# Usage: uv run ansible-playbook playbooks/infrastructure/consul-nomad/enable-service-identity.yml -i inventory/doggos-homelab/infisical.proxmox.yml

- name: Enable Service Identity Requirement in Nomad
  hosts: tag_nomad
  become: true

  tasks:
    - name: Update Nomad configuration to enable service identity
      ansible.builtin.replace:
        path: /etc/nomad.d/nomad.hcl
        regexp: '(\s+service_identity\s*{\s*\n\s*enabled\s*=\s*)false'
        replace: '\1true'
      register: config_updated

    - name: Update task identity setting
      ansible.builtin.replace:
        path: /etc/nomad.d/nomad.hcl
        regexp: '(\s+task_identity\s*{\s*\n\s*enabled\s*=\s*)false'
        replace: '\1true'
      register: task_config_updated

    - name: Restart Nomad if configuration changed
      ansible.builtin.systemd:
        name: nomad
        state: restarted
        daemon_reload: true
      when: config_updated.changed or task_config_updated.changed

    - name: Wait for Nomad to be ready
      ansible.builtin.wait_for:
        port: 4646
        host: "{{ ansible_default_ipv4.address }}"
        delay: 5
        timeout: 30
      when: config_updated.changed or task_config_updated.changed

- name: Verify Configuration
  hosts: nomad-server-1-lloyd

  tasks:
    - name: Check Nomad server status
      ansible.builtin.command: nomad server members
      register: nomad_status
      changed_when: false

    - name: Display status
      ansible.builtin.debug:
        msg:
          - "Service identity requirement enabled!"
          - ""
          - "Nomad server status:"
          - "{{ nomad_status.stdout_lines }}"
