---
# Consul ACL management tasks for Nomad integration
# This file manages Consul ACL policies and tokens for Nomad servers and clients

- name: Check if Consul ACL integration is enabled
  ansible.builtin.debug:
    msg: "Managing Consul ACL integration for Nomad {{ 'server' if nomad_server_enabled else 'client' }}"
  when: nomad_consul_manage_acls | bool

- name: Ensure management token is available
  ansible.builtin.fail:
    msg: |
      Consul management token is required for ACL management.
      Please set nomad_consul_management_token variable.
      You can get this token from:
      1. Initial Consul bootstrap
      2. Infisical at /consul/tokens/management
      3. Your secure password manager
  when:
    - nomad_consul_manage_acls | bool
    - nomad_consul_management_token == ""

- name: Create Nomad server ACL policy
  ansible.builtin.uri:
    url: 'http://{{ nomad_consul_address }}/v1/acl/policy'
    method: PUT
    headers:
      X-Consul-Token: '{{ nomad_consul_management_token }}'
    body_format: json
    body:
      Name: 'nomad-server'
      Description: 'Policy for Nomad servers with KV access'
      Rules: "{{ lookup('file', 'consul-policies/nomad-server.hcl') }}"
  register: nomad_server_policy_result
  failed_when: false
  when:
    - nomad_consul_manage_acls | bool
    - nomad_server_enabled | bool
  delegate_to: "{{ groups['consul'][0] | default(inventory_hostname) }}"
  run_once: true

- name: Create Nomad client ACL policy
  ansible.builtin.uri:
    url: 'http://{{ nomad_consul_address }}/v1/acl/policy'
    method: PUT
    headers:
      X-Consul-Token: '{{ nomad_consul_management_token }}'
    body_format: json
    body:
      Name: 'nomad-client'
      Description: 'Policy for Nomad clients with KV access'
      Rules: "{{ lookup('file', 'consul-policies/nomad-client.hcl') }}"
  register: nomad_client_policy_result
  failed_when: false
  when: nomad_consul_manage_acls | bool
  delegate_to: "{{ groups['consul'][0] | default(inventory_hostname) }}"
  run_once: true

- name: Create token for Nomad servers
  ansible.builtin.uri:
    url: 'http://{{ nomad_consul_address }}/v1/acl/token'
    method: PUT
    headers:
      X-Consul-Token: '{{ nomad_consul_management_token }}'
    body_format: json
    body:
      Description: 'Token for Nomad server integration with KV access'
      Policies:
        - Name: 'nomad-server'
      ServiceIdentities:
        - ServiceName: '{{ nomad_consul_server_service_name }}'
  register: nomad_server_token_result
  when:
    - nomad_consul_manage_acls | bool
    - nomad_server_enabled | bool
  delegate_to: "{{ groups['consul'][0] | default(inventory_hostname) }}"
  run_once: true

- name: Create token for Nomad clients
  ansible.builtin.uri:
    url: 'http://{{ nomad_consul_address }}/v1/acl/token'
    method: PUT
    headers:
      X-Consul-Token: '{{ nomad_consul_management_token }}'
    body_format: json
    body:
      Description: 'Token for Nomad client integration with KV access'
      Policies:
        - Name: 'nomad-client'
      ServiceIdentities:
        - ServiceName: '{{ nomad_consul_client_service_name }}'
  register: nomad_client_token_result
  when:
    - nomad_consul_manage_acls | bool
    - nomad_client_enabled | bool
  delegate_to: "{{ groups['consul'][0] | default(inventory_hostname) }}"

- name: Set server token fact
  ansible.builtin.set_fact:
    consul_acl_nomad_server_token: '{{ nomad_server_token_result.json.SecretID }}'
  when:
    - nomad_consul_manage_acls | bool
    - nomad_server_enabled | bool
    - nomad_server_token_result is defined
    - nomad_server_token_result.json is defined

- name: Set client token fact
  ansible.builtin.set_fact:
    consul_acl_nomad_client_token: '{{ nomad_client_token_result.json.SecretID }}'
  when:
    - nomad_consul_manage_acls | bool
    - nomad_client_enabled | bool
    - nomad_client_token_result is defined
    - nomad_client_token_result.json is defined

- name: Display token information for servers
  ansible.builtin.debug:
    msg:
      - '=== CONSUL ACL TOKEN CREATED ==='
      - 'Nomad Server Token: {{ consul_acl_nomad_server_token }}'
      - 'Store this token securely!'
  when:
    - nomad_consul_manage_acls | bool
    - nomad_server_enabled | bool
    - consul_acl_nomad_server_token is defined

- name: Display token information for clients
  ansible.builtin.debug:
    msg:
      - '=== CONSUL ACL TOKEN CREATED ==='
      - 'Nomad Client Token: {{ consul_acl_nomad_client_token }}'
      - 'Store this token securely!'
  when:
    - nomad_consul_manage_acls | bool
    - nomad_client_enabled | bool
    - consul_acl_nomad_client_token is defined
