---

- name: Assert homelab_domain is configured and not .local
  ansible.builtin.assert:
    that:
      - homelab_domain is defined
      - homelab_domain is string
      - homelab_domain | length > 0
      - homelab_domain is not match("\.local$")
    fail_msg: "homelab_domain must be set in inventory group_vars and must not end with .local"
    success_msg: "homelab_domain is properly configured: {{ homelab_domain }}"

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

- name: Include installation steps
  ansible.builtin.import_tasks: install.yml

- name: Include LXC integration (Nomad client only)
  ansible.builtin.import_tasks: lxc.yml
  when: nomad_client_enabled | bool

- name: Include Consul CNI and plugins
  ansible.builtin.import_tasks: cni.yml
  when: nomad_client_enabled | bool

- name: Install dynamic volumes plugin and unit (Nomad client only)
  ansible.builtin.import_tasks: dynamic-volumes.yml
  when: nomad_client_enabled | bool

- name: Include Consul ACL management (if enabled)
  ansible.builtin.import_tasks: consul-acl.yml
  when: nomad_consul_manage_acls | default(true)

- name: Include configuration templating
  ansible.builtin.import_tasks: config.yml

- name: Include TLS and service checks
  ansible.builtin.import_tasks: validate.yml

- name: Enable and start Nomad service
  ansible.builtin.systemd:
    name: nomad
    state: "{{ nomad_service_state }}"
    enabled: "{{ nomad_service_enabled }}"
    daemon_reload: true
  become: true
