---
# Handlers for Vault role

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart vault
  ansible.builtin.systemd:
    name: '{{ vault_service_name }}'
    state: restarted
    daemon_reload: true
  when: vault_service_state == "started"

- name: reload vault
  ansible.builtin.systemd:
    name: '{{ vault_service_name }}'
    state: reloaded
  when: vault_service_state == "started"

- name: unseal vault
  ansible.builtin.shell: |
    if vault status 2>/dev/null | grep -q "Sealed.*true"; then
      echo "Vault is sealed. Manual unseal required."
      exit 0
    fi
  environment:
    VAULT_ADDR: '{{ vault_api_addr }}'
  when:
    - vault_mode == "production"
    - not vault_auto_unseal_enabled | bool
