---
# PowerDNS Secret Generation
# This playbook generates the necessary secrets for PowerDNS deployment

- name: Generate PowerDNS secrets
  hosts: localhost
  gather_facts: no
  
  vars:
    # Generate random passwords
    mysql_root_password: "{{ lookup('password', '/tmp/powerdns_mysql_root chars=ascii_letters,digits length=32') }}"
    mysql_user_password: "{{ lookup('password', '/tmp/powerdns_mysql_user chars=ascii_letters,digits length=32') }}"
    powerdns_api_key: "{{ lookup('password', '/tmp/powerdns_api chars=ascii_letters,digits,hexdigits length=48') }}"
    
  tasks:
    - name: Display generated secrets
      debug:
        msg: |
          PowerDNS secrets have been generated!
          
          ============================================
          SAVE THESE SECRETS - They won't be shown again
          ============================================
          
          MySQL Root Password: {{ mysql_root_password }}
          MySQL User Password: {{ mysql_user_password }}
          PowerDNS API Key: {{ powerdns_api_key }}
          
          ============================================
          
          To set these in Consul KV, SSH to a Nomad server and run:
          
          export CONSUL_HTTP_TOKEN="your-consul-management-token"
          
          consul kv put powerdns/mysql/root_password "{{ mysql_root_password }}"
          consul kv put powerdns/mysql/password "{{ mysql_user_password }}"
          consul kv put powerdns/api/key "{{ powerdns_api_key }}"
          
          ============================================
          
          Or save them to Infisical at:
          /apollo-13/powerdns/MYSQL_ROOT_PASSWORD
          /apollo-13/powerdns/MYSQL_USER_PASSWORD
          /apollo-13/powerdns/API_KEY
          
    - name: Save secrets to local file (for reference)
      copy:
        content: |
          # PowerDNS Secrets - Generated {{ ansible_date_time.iso8601 }}
          # KEEP THIS FILE SECURE!
          
          MYSQL_ROOT_PASSWORD={{ mysql_root_password }}
          MYSQL_USER_PASSWORD={{ mysql_user_password }}
          POWERDNS_API_KEY={{ powerdns_api_key }}
          
          # Consul KV Commands:
          consul kv put powerdns/mysql/root_password "{{ mysql_root_password }}"
          consul kv put powerdns/mysql/password "{{ mysql_user_password }}"
          consul kv put powerdns/api/key "{{ powerdns_api_key }}"
        dest: /tmp/powerdns-secrets.txt
        mode: '0600'
        
    - name: Display file location
      debug:
        msg: "Secrets have been saved to: /tmp/powerdns-secrets.txt (mode 0600)"