---
# PowerDNS Secret Setup for Consul KV
# This playbook creates the necessary secrets for PowerDNS deployment

- name: Set up PowerDNS secrets in Consul KV
  hosts: nomad-server-1
  gather_facts: false

  vars:
    # Generate random passwords - these will be different each run unless already set
    mysql_root_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
    mysql_user_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
    powerdns_api_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=48') }}"

  tasks:
    - name: Get Consul management token from environment
      set_fact:
        consul_token: "{{ lookup('env', 'CONSUL_HTTP_TOKEN') }}"
      no_log: true

    - name: Check if we have a token
      fail:
        msg: 'CONSUL_HTTP_TOKEN environment variable not set. Please export it before running this playbook.'
      when: consul_token == ""

    - name: Check if secrets already exist
      command: consul kv get -token={{ consul_token }} powerdns/mysql/root_password
      register: existing_secret
      failed_when: false
      changed_when: false
      no_log: true

    - name: Display warning if secrets exist
      debug:
        msg: 'WARNING: PowerDNS secrets already exist in Consul KV. They will NOT be overwritten.'
      when: existing_secret.rc == 0

    - name: Create PowerDNS secrets in Consul KV
      command: 'consul kv put -token={{ consul_token }} {{ item.key }} {{ item.value }}'
      loop:
        - { key: 'powerdns/mysql/root_password', value: '{{ mysql_root_password }}' }
        - { key: 'powerdns/mysql/password', value: '{{ mysql_user_password }}' }
        - { key: 'powerdns/api/key', value: '{{ powerdns_api_key }}' }
      when: existing_secret.rc != 0
      no_log: true # Don't log passwords

    - name: Verify secrets were created
      command: 'consul kv get -token={{ consul_token }} {{ item }}'
      loop:
        - powerdns/mysql/root_password
        - powerdns/mysql/password
        - powerdns/api/key
      register: verify_secrets
      failed_when: verify_secrets.rc != 0
      changed_when: false
      no_log: true

    - name: Display completion message
      debug:
        msg: |
          PowerDNS secrets have been configured in Consul KV.

          The following keys are now available:
          - powerdns/mysql/root_password
          - powerdns/mysql/password
          - powerdns/api/key

          These will be used by the PowerDNS Nomad job.
