---
- name: Install repository for Debian-based systems
  when: ansible_os_family == "Debian"
  block:
    - name: Install repository dependencies
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Netdata GPG key
      ansible.builtin.apt_key:
        url: 'https://packagecloud.io/netdata/netdata/gpgkey'
        state: present

    - name: Add Netdata repository
      ansible.builtin.apt_repository:
        repo: 'deb https://packagecloud.io/netdata/netdata-repoconfig/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main'
        state: present
        filename: netdata

    - name: Install Netdata package
      ansible.builtin.apt:
        name: '{{ netdata_package_name }}'
        state: present
        update_cache: true

- name: Install repository for RedHat-based systems
  when: ansible_os_family == "RedHat"
  block:
    - name: Install repository package
      ansible.builtin.yum:
        name: 'https://packagecloud.io/netdata/netdata-repoconfig/el/{{ ansible_distribution_major_version }}/x86_64/netdata-repo-{{ netdata_repository_channel }}-1.noarch.rpm'
        state: present
        disable_gpg_check: false

    - name: Install Netdata package
      ansible.builtin.yum:
        name: '{{ netdata_package_name }}'
        state: present
        update_cache: true
