---
- name: Working Example - Using 1Password Connect API
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    connect_host: "{{ lookup('env', 'OP_CONNECT_HOST') }}"
    connect_token: "{{ lookup('env', 'OP_CONNECT_TOKEN') }}"
    vault_id: "{{ lookup('env', 'OP_VAULT_ID') }}"

  tasks:
    - name: Create a custom lookup filter for 1Password Connect
      ansible.builtin.set_fact:
        op_connect_headers:
          Authorization: "Bearer {{ connect_token }}"
          Content-Type: "application/json"

    - name: Retrieve Proxmox credentials from Connect
      block:
        - name: Get item by title
          ansible.builtin.uri:
            url: "{{ connect_host }}/v1/vaults/{{ vault_id }}/items"
            method: GET
            headers: "{{ op_connect_headers }}"
            timeout: 10
          register: items_response

        - name: Find Proxmox item
          ansible.builtin.set_fact:
            proxmox_item_id: >-
              {{ (items_response.json | selectattr('title', 'equalto', 'Proxmox API - og-homelab')
                 | first).id }}

        - name: Get full item details
          ansible.builtin.uri:
            url: "{{ connect_host }}/v1/vaults/{{ vault_id }}/items/{{ proxmox_item_id }}"
            method: GET
            headers: "{{ op_connect_headers }}"
            timeout: 10
          register: item_details

        - name: Extract credentials
          ansible.builtin.set_fact:
            proxmox_url: "{{ (item_details.json.fields | selectattr('label', 'equalto', 'url') | first).value }}"
            proxmox_user: "{{ (item_details.json.fields | selectattr('label', 'equalto', 'username') | first).value }}"
            proxmox_token_id: >-
              {{ (item_details.json.fields | selectattr('label', 'equalto', 'token_id') | first).value }}
            proxmox_token_secret: >-
              {{ (item_details.json.fields | selectattr('label', 'equalto', 'token_secret') | first).value }}

        - name: Display retrieved credentials (masked)
          ansible.builtin.debug:
            msg:
              - "✅ Successfully retrieved Proxmox credentials from 1Password Connect"
              - "URL: {{ proxmox_url }}"
              - "User: {{ proxmox_user }}"
              - "Token ID: {{ proxmox_token_id }}"
              - "Token Secret: {{ proxmox_token_secret | regex_replace('(.{4}).*(.{4})$', '\\1...\\2') }}"

    - name: Example - Use credentials to test Proxmox connection
      ansible.builtin.uri:
        url: "{{ proxmox_url }}/api2/json/nodes"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ proxmox_user }}!{{ proxmox_token_id }}={{ proxmox_token_secret }}"
        validate_certs: false
        timeout: 10
      register: proxmox_test

    - name: Show Proxmox nodes
      ansible.builtin.debug:
        msg:
          - "✅ Successfully connected to Proxmox using credentials from 1Password Connect"
          - "Found {{ proxmox_test.json.data | length }} nodes"
          - "Nodes: {{ proxmox_test.json.data | map(attribute='node') | list | join(', ') }}"
