---
# Example: Using Consul with ACL token from 1Password
- name: Consul Operations with 1Password ACL Token
  hosts: localhost
  gather_facts: false
  vars:
    # Retrieve Consul ACL token from 1Password
    consul_acl_token: >-
      {{ lookup('community.general.onepassword', 'Consul ACL - doggos-homelab',
                field='token', vault='DevOps') }}
    consul_url: >-
      {{ lookup('community.general.onepassword', 'Consul ACL - doggos-homelab',
                field='url', vault='DevOps') }}

  tasks:
    - name: Example - List Consul services using token
      ansible.builtin.uri:
        url: "{{ consul_url }}/v1/catalog/services"
        method: GET
        headers:
          X-Consul-Token: "{{ consul_acl_token }}"
        validate_certs: false
      register: consul_services

    - name: Display services
      ansible.builtin.debug:
        msg: "Consul services: {{ consul_services.json.keys() | list }}"

    - name: Example - Check Consul cluster health
      ansible.builtin.uri:
        url: "{{ consul_url }}/v1/status/leader"
        method: GET
        headers:
          X-Consul-Token: "{{ consul_acl_token }}"
        validate_certs: false
      register: consul_leader

    - name: Display leader
      ansible.builtin.debug:
        msg: "Consul leader: {{ consul_leader.json }}"

    - name: Example - Use token in command module
      ansible.builtin.command: consul members
      changed_when: false
      environment:
        CONSUL_HTTP_TOKEN: "{{ consul_acl_token }}"
        CONSUL_HTTP_ADDR: "{{ consul_url }}"
      delegate_to: "{{ groups['nomad_servers'][0] | default('localhost') }}"
      when: groups['nomad_servers'] is defined

# Example of using the token in a role or task file:
# vars:
#   consul_token: >-
#     {{ lookup('community.general.onepassword', 'Consul ACL - doggos-homelab',
#               field='token', vault='DevOps') }}
#
# Or in inventory:
# [consul:vars]
# consul_acl_token=>-
#   {{ lookup('community.general.onepassword', 'Consul ACL - doggos-homelab',
#             field='token', vault='DevOps') }}
