---
# Minimal test for Infisical integration
- name: Test Infisical Lookup
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Debug environment variables
      debug:
        msg: |
          CLIENT_ID length: {{ lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_ID') | length }}
          SECRET length: {{ lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET') | length }}
    
    - name: Test Infisical CLI directly
      command: infisical secrets get CONSUL_MASTER_TOKEN --env=prod --path="/apollo-13/consul/" --plain
      register: cli_result
      changed_when: false
      no_log: true
    
    - name: Show CLI works
      debug:
        msg: "CLI returned token starting with: {{ cli_result.stdout[:10] }}..."
      no_log: true
    
    - name: Test Infisical lookup with explicit parameters
      set_fact:
        consul_token: "{{ lookup('infisical.vault.read_secrets',
                          auth_method='universal_auth',
                          universal_auth_client_id=lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_ID'),
                          universal_auth_client_secret=lookup('env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET'),
                          project_id='7b832220-24c0-45bc-a5f1-ce9794a31259',
                          env_slug='prod',
                          path='/apollo-13/consul',
                          secret_name='CONSUL_MASTER_TOKEN',
                          url='https://app.infisical.com') }}"
      no_log: true
    
    - name: Show lookup works
      debug:
        msg: "Lookup successful - token retrieved"
      when: consul_token is defined