---
# Store Proxmox API Token for doggos-homelab cluster in 1Password
#
# Prerequisites:
# - 1Password Connect server running and accessible
# - OP_CONNECT_HOST and OP_CONNECT_TOKEN environment variables set
# - onepassword.connect collection installed (ansible-galaxy collection install onepassword.connect)
#
# Usage:
# ansible-playbook playbooks/examples/create-proxmox-secret-doggos.yml

- name: Store Proxmox API Token for doggos-homelab in 1Password
  hosts: localhost
  gather_facts: false
  vars:
    # Get Connect server details from environment
    op_connect_host: "{{ lookup('env', 'OP_CONNECT_HOST') }}"
    op_connect_token: "{{ lookup('env', 'OP_CONNECT_TOKEN') }}"

    # Vault ID - can be set via environment or specify directly
    vault_id: "{{ lookup('env', 'OP_VAULT_ID') | default('your-vault-id-here') }}"

    # Item configuration for doggos-homelab cluster
    proxmox_url: "https://192.168.10.2:8006"
    proxmox_user: "ansible@pve"
    proxmox_token_id: "service"
    cluster_name: "doggos-homelab"

  tasks:
    - name: Prompt for Proxmox token secret
      ansible.builtin.pause:
        prompt: "Enter the Proxmox API token secret for {{ cluster_name }}"
        echo: false
      register: token_prompt
      when: proxmox_token_secret is not defined

    - name: Set token secret from prompt
      ansible.builtin.set_fact:
        proxmox_token_secret: "{{ token_prompt.user_input }}"
      when: token_prompt.user_input is defined

    - name: Create Proxmox API credentials in 1Password
      onepassword.connect.generic_item:
        hostname: "{{ op_connect_host }}"
        token: "{{ op_connect_token }}"
        vault_id: "{{ vault_id }}"
        title: "Proxmox API - {{ cluster_name }}"
        category: "api_credential"
        state: present
        fields:
          - label: "url"
            field_type: "string"
            value: "{{ proxmox_url }}"
          - label: "username"
            field_type: "string"
            value: "{{ proxmox_user }}"
          - label: "token_id"
            field_type: "string"
            value: "{{ proxmox_token_id }}"
          - label: "token_secret"
            field_type: "concealed"
            value: "{{ proxmox_token_secret }}"
        tags:
          - "proxmox"
          - "ansible"
          - "api"
          - "{{ cluster_name }}"
      no_log: true
      register: proxmox_secret

    - name: Display success message
      ansible.builtin.debug:
        msg:
          - "✅ Secret successfully created in 1Password!"
          - "Item: {{ proxmox_secret.op_item.title }}"
          - "UUID: {{ proxmox_secret.op_item.id }}"
          - ""
          - "You can now use this in your inventory with:"
          - "token_secret: \"{{ '{{' }} lookup('community.general.onepassword', "
          - "  '{{ proxmox_secret.op_item.title }}', field='token_secret') {{ '}}' }}\""
