---
# Check PBS Netdata logs more thoroughly

- name: Check PBS logs
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Add PBS to inventory
      ansible.builtin.add_host:
        name: pbs
        ansible_host: 192.168.30.200
        ansible_user: root
        ansible_password: "{{ vault_pbs_password }}"

- name: Find and check Netdata logs
  hosts: pbs
  become: true
  gather_facts: false

  tasks:
    - name: Find all Netdata related files
      ansible.builtin.shell: |
        echo "=== Netdata config files ==="
        ls -la /etc/netdata/ 2>/dev/null | head -10
        echo ""
        echo "=== Looking for log files ==="
        find /var -name "*netdata*" -type f 2>/dev/null | grep -v ".db" | head -20
        echo ""
        echo "=== Checking Netdata data directory ==="
        ls -la /var/cache/netdata/ 2>/dev/null | head -10
      register: netdata_files
      changed_when: false

    - name: Display Netdata files
      ansible.builtin.debug:
        msg: "{{ netdata_files.stdout_lines }}"

    - name: Check if Netdata has error output
      ansible.builtin.shell: |
        if [ -f /var/cache/netdata/netdata-updater.log ]; then
          echo "=== Updater log ==="
          tail -20 /var/cache/netdata/netdata-updater.log
        fi
        echo ""
        echo "=== Checking systemd journal with more detail ==="
        journalctl -u netdata --since "5 minutes ago" --no-pager -o cat | grep -v "NETDATA_START_COMMAND" | head -30
      register: error_logs
      changed_when: false

    - name: Display error logs
      ansible.builtin.debug:
        msg: "{{ error_logs.stdout_lines }}"

    - name: Test streaming manually
      ansible.builtin.shell: |
        # Try to manually test the connection
        echo "=== Testing API key acceptance ==="
        echo -e "STREAM key=og-child-key\n" | timeout 3 nc 192.168.30.50 19999 2>&1 || echo "Connection test done"
      register: manual_test
      changed_when: false
      failed_when: false

    - name: Display manual test
      ansible.builtin.debug:
        msg: "{{ manual_test.stdout_lines }}"

    - name: Check Netdata internal API
      ansible.builtin.uri:
        url: "http://127.0.0.1:19999/api/v1/info"
        method: GET
      register: netdata_info
      failed_when: false

    - name: Display Netdata info
      ansible.builtin.debug:
        msg:
          - "Netdata running: {{ 'Yes' if netdata_info.status == 200 else 'No' }}"
          - "Version: {{ netdata_info.json.version | default('Unknown') }}"
          - "UID: {{ netdata_info.json.uid | default('Unknown') }}"
