---
# Debug PBS Netdata streaming

- name: Debug PBS Netdata
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Add PBS to inventory
      ansible.builtin.add_host:
        name: pbs
        ansible_host: 192.168.30.200
        ansible_user: root
        ansible_password: "{{ vault_pbs_password }}"

- name: Debug Netdata on PBS
  hosts: pbs
  become: true
  gather_facts: false

  tasks:
    - name: Stop Netdata temporarily
      ansible.builtin.systemd:
        name: netdata
        state: stopped

    - name: Start Netdata in debug mode for streaming
      ansible.builtin.shell: |
        timeout 10 /usr/sbin/netdata -D -W set2 stream enabled=yes 2>&1 | grep -E "(stream|connect|api.key|192.168.30.50|error)" | head -50 || echo "Debug output captured"
      register: debug_output
      changed_when: false
      failed_when: false

    - name: Display debug output
      ansible.builtin.debug:
        msg: "{{ debug_output.stdout_lines }}"

    - name: Start Netdata normally
      ansible.builtin.systemd:
        name: netdata
        state: started
        daemon_reload: true

    - name: Wait a moment
      ansible.builtin.pause:
        seconds: 5

    - name: Check if streaming started
      ansible.builtin.shell: |
        # Check with ss (more detailed than netstat)
        echo "=== Socket connections ==="
        ss -tn | grep "192.168.30.50:19999" || echo "No connection found with ss"
        echo ""
        echo "=== Recent journal entries ==="
        journalctl -u netdata -n 20 --no-pager | tail -10
      register: final_check
      changed_when: false

    - name: Display final status
      ansible.builtin.debug:
        msg: "{{ final_check.stdout_lines }}"
