---
- name: Dump stream.conf from all nodes
  hosts: all:!localhost
  become: true
  gather_facts: false

  tasks:
    - name: Read stream.conf
      slurp:
        src: /etc/netdata/stream.conf
      register: stream_conf
      failed_when: false

    - name: Display stream.conf content
      debug:
        msg: |
          === {{ inventory_hostname }} ({{ ansible_host | default('N/A') }}) ===
          {{ stream_conf.content | b64decode | default('File not found') }}
