---
# Restart PBS and check streaming

- name: Restart PBS and check
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Add PBS to inventory
      ansible.builtin.add_host:
        name: pbs
        ansible_host: 192.168.30.200
        ansible_user: root
        ansible_password: "{{ vault_pbs_password }}"

- name: Restart PBS Netdata
  hosts: pbs
  become: true
  gather_facts: false

  tasks:
    - name: Restart Netdata
      ansible.builtin.systemd:
        name: netdata
        state: restarted

    - name: Wait for startup
      ansible.builtin.pause:
        seconds: 10

    - name: Check streaming status
      ansible.builtin.shell: |
        echo "=== Checking connection to pve1 ==="
        ss -tn | grep "192.168.30.50:19999" || echo "No connection"
        echo ""
        echo "=== Netdata logs ==="
        journalctl -u netdata --since "30 seconds ago" --no-pager | tail -20
      register: pbs_status
      changed_when: false

    - name: Display PBS status
      ansible.builtin.debug:
        msg: "{{ pbs_status.stdout_lines }}"

- name: Check pve1 logs
  hosts: pve1
  become: true
  gather_facts: false

  tasks:
    - name: Check recent connection attempts
      ansible.builtin.shell: |
        echo "=== Recent streaming logs on pve1 ==="
        journalctl -u netdata --since "1 minute ago" --no-pager | grep -E "(STREAM|pbs|og-child-key|192.168.30.200)" | tail -30
      register: pve1_logs
      changed_when: false

    - name: Display pve1 logs
      ansible.builtin.debug:
        msg: "{{ pve1_logs.stdout_lines }}"
