---
galaxy_info:
  author: NetBox Ansible Team
  description: Configure DNS resolution for Consul service discovery
  company: Homelab
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm

dependencies: []