---
# Deploy Netdata child configuration to og-homelab nodes
# This configures nodes to stream to pve1

- name: Deploy Netdata child configuration
  hosts: dockerhost
  become: true
  gather_facts: true
  
  tasks:
    - name: Install Netdata if not present
      ansible.builtin.package:
        name: netdata
        state: present
    
    - name: Create streaming configuration
      ansible.builtin.copy:
        content: |
          # Netdata streaming configuration for og-homelab child nodes
          [stream]
              enabled = yes
              destination = 192.168.30.50:19999
              api key = {{ vault_netdata_parent_api_key_og | default('og-child-key') }}
              timeout seconds = 60
              default port = 19999
              send charts matching = *
              buffer size bytes = 1048576
              reconnect delay seconds = 5
              initial clock resync iterations = 2
        dest: /etc/netdata/stream.conf
        owner: netdata
        group: netdata
        mode: '0640'
        backup: true
    
    - name: Configure Netdata for minimal resource usage
      ansible.builtin.copy:
        content: |
          [global]
              memory mode = ram
              history = 1800
              update every = 2
              
          [web]
              enabled = no
              
          [plugins]
              apps = no
              cgroups = yes
              charts.d = no
              checks = no
              diskspace = yes
              ebpf = no
              fping = no
              go.d = no
              idlejitter = no
              ioping = no
              nfacct = no
              perf = no
              proc = yes
              python.d = no
              slabinfo = no
              statsd = no
              tc = no
              timex = no
        dest: /etc/netdata/netdata.conf
        owner: netdata
        group: netdata
        mode: '0640'
        backup: true
    
    - name: Restart Netdata
      ansible.builtin.systemd:
        name: netdata
        state: restarted
        daemon_reload: true
    
    - name: Verify streaming
      ansible.builtin.wait_for:
        timeout: 10
      
    - name: Check streaming status
      ansible.builtin.shell: |
        grep -q "connected to" /var/log/netdata/error.log 2>/dev/null || echo "Not streaming yet"
      register: stream_status
      changed_when: false
    
    - name: Display status
      ansible.builtin.debug:
        msg: "Streaming status: {{ stream_status.stdout }}"