---
# Fix pve1 streaming authentication

- name: Fix pve1 streaming authentication
  hosts: pve1
  become: true
  gather_facts: false

  tasks:
    - name: Update stream.conf with proper API key configuration
      ansible.builtin.copy:
        content: |
          # Netdata streaming configuration for pve1
          # This parent accepts streams from og-homelab children and mesh replication from doggos parents

          [stream]
              enabled = yes
              destination = 192.168.10.11:19999 192.168.10.12:19999 192.168.10.13:19999
              api key = netdata-parent-mesh-key
              timeout seconds = 60
              default port = 19999
              send charts matching = *
              buffer size bytes = 1048576
              reconnect delay seconds = 5
              initial clock resync iterations = 2

          # Accept child streams from og-homelab nodes
          [og-child-key]
              type = api
              enabled = yes
              default history = 3600
              default memory mode = dbengine
              health enabled by default = auto
              allow from = 192.168.30.0/24
              default postpone alarms on connect seconds = 60
              multiple connections = allow

          # Parent mesh replication
          [netdata-parent-mesh-key]
              type = api
              enabled = yes
              default history = 3600
              default memory mode = dbengine
              health enabled by default = auto
              allow from = 192.168.10.0/24 192.168.30.0/24
              default postpone alarms on connect seconds = 60
              multiple connections = allow
        dest: /etc/netdata/stream.conf
        owner: netdata
        group: netdata
        mode: '0640'
        backup: true

    - name: Restart Netdata
      ansible.builtin.systemd:
        name: netdata
        state: restarted
        daemon_reload: true

    - name: Wait for Netdata to start
      ansible.builtin.wait_for:
        port: 19999
        host: "{{ ansible_host }}"
        timeout: 30

    - name: Check logs after restart
      ansible.builtin.shell: |
        sleep 5
        journalctl -u netdata -n 30 --no-pager | grep -E "(STREAM|accepted|connected)" | tail -20 || echo "No streaming entries yet"
      register: log_check
      changed_when: false

    - name: Display logs
      ansible.builtin.debug:
        msg: "{{ log_check.stdout_lines }}"
