---
# Fix pve1 API key configuration with correct format

- name: Fix pve1 API key configuration
  hosts: pve1
  become: true
  gather_facts: false
  
  tasks:
    - name: Backup current stream.conf
      ansible.builtin.copy:
        src: /etc/netdata/stream.conf
        dest: /etc/netdata/stream.conf.backup-{{ ansible_date_time.epoch }}
        remote_src: true
      ignore_errors: true
    
    - name: Create properly formatted stream.conf
      ansible.builtin.copy:
        content: |
          # Netdata streaming configuration for pve1
          # This parent accepts streams from og-homelab children and mesh replication from doggos parents
          
          [stream]
              enabled = yes
              destination = 192.168.10.11:19999 192.168.10.12:19999 192.168.10.13:19999
              api key = netdata-parent-mesh-key
              timeout seconds = 60
              default port = 19999
              send charts matching = *
              buffer size bytes = 1048576
              reconnect delay seconds = 5
              initial clock resync iterations = 2
          
          # Accept child streams from og-homelab nodes
          [og-child-key]
              enabled = yes
              default history = 3600
              default memory mode = dbengine
              health enabled by default = auto
              allow from = *
              default postpone alarms on connect seconds = 60
              multiple connections = allow
          
          # Parent mesh replication  
          [netdata-parent-mesh-key]
              enabled = yes
              default history = 3600
              default memory mode = dbengine
              health enabled by default = auto
              allow from = *
              default postpone alarms on connect seconds = 60
              multiple connections = allow
        dest: /etc/netdata/stream.conf
        owner: netdata
        group: netdata
        mode: '0640'
        backup: true
    
    - name: Restart Netdata
      ansible.builtin.systemd:
        name: netdata
        state: restarted
        daemon_reload: true
    
    - name: Wait for Netdata to start
      ansible.builtin.wait_for:
        port: 19999
        host: "{{ ansible_host }}"
        timeout: 30
    
    - name: Wait for connections
      ansible.builtin.pause:
        seconds: 10
    
    - name: Check for streaming connections
      ansible.builtin.shell: |
        echo "=== Active streaming connections ==="
        netstat -an | grep ":19999.*ESTABLISHED" | grep -v "127.0.0.1"
        echo ""
        echo "=== Recent streaming logs ==="
        journalctl -u netdata --since "1 minute ago" --no-pager | grep -E "(STREAM.*accepted|connected from|api.key.*accepted)" | tail -20
      register: stream_status
      changed_when: false
    
    - name: Display streaming status
      ansible.builtin.debug:
        msg: "{{ stream_status.stdout_lines }}"