---
galaxy_info:
  role_name: nfs
  author: Your Organization
  description: Configures NFS client functionality
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye

  galaxy_tags:
    - nfs
    - storage
    - filesharing

dependencies:
  - role: bootstrap
