---
# Enable dynamic host volumes on Nomad clients
# This playbook configures Nomad clients to support dynamic volume provisioning
#
# Usage:
# ansible-playbook enable-dynamic-volumes.yml -i inventory/doggos-homelab/infisical.proxmox.yml

- name: Enable Dynamic Host Volumes on Nomad Clients
  hosts: tag_client
  become: true

  vars:
    dynamic_volumes_base: /opt/nomad/volumes/dynamic
    plugin_scripts_dir: /opt/nomad/plugins

  tasks:
    - name: Ensure base directories exist
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - '/opt/nomad/volumes/dynamic/.registry'
        - '/opt/nomad/plugins'

    - name: Install dynamic volumes plugin and unit via role
      ansible.builtin.import_role:
        name: nomad
        tasks_from: dynamic-volumes.yml
