---
# Main tasks for consul_dns role

- name: Assert homelab_domain is configured and not .local
  ansible.builtin.assert:
    that:
      - homelab_domain is defined
      - homelab_domain is string
      - homelab_domain | length > 0
      - homelab_domain is not match("\.local$")
    fail_msg: "homelab_domain must be set in inventory group_vars and must not end with .local"
    success_msg: "homelab_domain is properly configured: {{ homelab_domain }}"

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  failed_when: false

- name: Configure DNS resolution method
  include_tasks: "{{ consul_dns_method }}.yml"
  when: consul_dns_method in ['systemd-resolved', 'dnsmasq', 'resolv']

- name: Register infrastructure services
  include_tasks: register_services.yml
  when:
    - consul_register_services | bool
    - inventory_hostname in groups['consul_servers']
    - inventory_hostname == groups['consul_servers'][0]

- name: Validate DNS resolution
  include_tasks: validate.yml
  tags:
    - validate
    - never
