---
# Configure systemd-resolved for Consul DNS

- name: Install systemd-resolved
  package:
    name: systemd-resolved
    state: present
  when: ansible_os_family == "Debian"

- name: Create systemd-resolved drop-in directory
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Configure systemd-resolved for Consul DNS
  template:
    src: consul-resolved.conf.j2
    dest: /etc/systemd/resolved.conf.d/consul.conf
    mode: '0644'
    owner: root
    group: root
  notify: restart systemd-resolved

- name: Enable and start systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: true
    state: started
    daemon_reload: true

- name: Update /etc/resolv.conf symlink
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
  when: ansible_os_family == "Debian"
