name: Security Scan

on:
  workflow_dispatch:
  # push:
  #   branches: [ main, develop ]
  # pull_request:
  #   branches: [ main ]
  # schedule:
    # Run security scan weekly on Monday at 9 AM UTC
   #  - cron: '0 9 * * 1'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Full history for scanning

      - name: Install Infisical CLI
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical

      - name: Run Infisical scan
        run: |
          infisical scan \
            --report-format sarif \
            --report-path infisical-results.sarif \
            --no-color \
            --verbose

      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: infisical-results.sarif
          category: secret-scanning

      - name: Upload scan results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: infisical-scan-results
          path: infisical-results.sarif
          retention-days: 30
